export type BlueprintMarkdownInput = {
  id: string;
  locale: "en" | "ar";
  projectTypes: string[];
  stage: string;
  roles: string[];
  workflows: string[];
  integrations: string[];
  intelligence: string[];
  priorities: string[];
  complexityLabel: string;
  scale: {
    users: string;
    locations: string;
    languages: string;
  };
  problemNarrative: string;
  interpretation: string;
  recommendation: string;
  contact?: {
    name: string;
    company: string;
    email: string;
  };
};

function bullets(items: string[], empty: string): string {
  if (!items.length) return `- ${empty}`;
  return items.map((item) => `- ${item}`).join("\n");
}

export function buildBlueprintMarkdown(input: BlueprintMarkdownInput): string {
  const isAr = input.locale === "ar";
  const empty = isAr ? "غير محدد" : "Not specified";
  const title = isAr
    ? `# مخطّط مشروع — ${input.id}`
    : `# Project Blueprint — ${input.id}`;

  const sections = isAr
    ? {
        summary: "## الملخص",
        project: "### نوع المشروع",
        stage: "### المرحلة",
        users: "## من يستخدم النظام",
        flows: "## ما يجب أن يحدث",
        integrations: "## التكاملات",
        intelligence: "## طبقة الذكاء",
        scale: "## المقياس",
        priorities: "## الأولويات",
        problem: "## المشكلة بكلمات العميل",
        reading: "## قراءة أركان",
        next: "## نقطة البداية المقترحة",
        meta: "## بيانات التواصل",
        usersScale: "المستخدمون",
        locations: "المواقع",
        languages: "اللغات",
        complexity: "التعقيد",
        company: "الشركة",
        email: "البريد",
        name: "الاسم",
      }
    : {
        summary: "## Summary",
        project: "### Project type",
        stage: "### Stage",
        users: "## Who uses the system",
        flows: "## What must happen",
        integrations: "## Integrations",
        intelligence: "## Intelligence layer",
        scale: "## Scale",
        priorities: "## Priorities",
        problem: "## Problem in the client’s words",
        reading: "## Arkan reading",
        next: "## Recommended starting point",
        meta: "## Contact",
        usersScale: "Users",
        locations: "Locations",
        languages: "Languages",
        complexity: "Complexity",
        company: "Company",
        email: "Email",
        name: "Name",
      };

  const lines = [
    title,
    "",
    `> ${isAr ? "ملف موجز أولي من أداة ابنِ مع أركان" : "Initial brief generated by Build with Arkan"}`,
    "",
    sections.summary,
    "",
    sections.project,
    bullets(input.projectTypes, empty),
    "",
    sections.stage,
    `- ${input.stage || empty}`,
    `- **${sections.complexity}:** ${input.complexityLabel}`,
    "",
    sections.users,
    bullets(input.roles, empty),
    "",
    sections.flows,
    bullets(input.workflows, empty),
    "",
    sections.integrations,
    bullets(input.integrations, empty),
    "",
    sections.intelligence,
    bullets(input.intelligence, empty),
    "",
    sections.scale,
    `- **${sections.usersScale}:** ${input.scale.users || empty}`,
    `- **${sections.locations}:** ${input.scale.locations || empty}`,
    `- **${sections.languages}:** ${input.scale.languages || empty}`,
    "",
    sections.priorities,
    bullets(input.priorities, empty),
    "",
    sections.problem,
    "",
    input.problemNarrative.trim() || empty,
    "",
    sections.reading,
    "",
    input.interpretation,
    "",
    sections.next,
    "",
    input.recommendation,
  ];

  if (input.contact?.name || input.contact?.email) {
    lines.push(
      "",
      sections.meta,
      `- **${sections.name}:** ${input.contact.name || empty}`,
      `- **${sections.company}:** ${input.contact.company || empty}`,
      `- **${sections.email}:** ${input.contact.email || empty}`,
    );
  }

  lines.push(
    "",
    "---",
    isAr
      ? `_أُنشئ بواسطة أركان · ${input.id}_`
      : `_Generated by Arkan · ${input.id}_`,
    "",
  );

  return lines.join("\n");
}

export function downloadMarkdownFile(filename: string, content: string) {
  if (typeof window === "undefined") return;
  const safeName = filename.replace(/[^\w.\-]+/g, "_");
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = safeName.endsWith(".md") ? safeName : `${safeName}.md`;
  anchor.rel = "noopener";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
