import type { Project } from "../types";
import {
  L,
  behind,
  integ,
  mod,
  role,
  scaleFromMass,
  techWhy,
  wf,
} from "../projectBuilders";

const mass = {
  modules: 8,
  roles: 6,
  workflows: 4,
  interfaces: 4,
  integrations: 3,
  automations: 3,
  dataDomains: 6,
  locations: 1,
} as const;

export const cairoQuarantine: Project = {
  id: "CQM-01",
  slug: "cairo-quarantine",
  title: L("Cairo Quarantine", "Cairo Quarantine"),
  descriptor: L("إدارة حالات حساسة", "Sensitive case operations"),
  summary: L(
    "منصة إدارية متعددة اللغات لخدمات الحجر الصحي: محتوى إرشادي، حجز مواعيد مع بطاقة QR، شكاوى مرتبطة بالمكاتب، ولوحة تشغيل بصلاحيات صارمة.",
    "A multilingual administrative platform for quarantine services: guidance content, appointment booking with QR cards, office-linked complaints, and an ops console with strict permissions.",
  ),
  context: L(
    "إدارة حجر صحي في القاهرة تخدم مسافرين دوليين وحجاجًا ومواطنين عبر مكاتب متعددة. الجمهور يحتاج معلومات موثوقة بعدة لغات، والمكاتب تحتاج سعة يومية وتتبع طلبات وحضورًا دون فوضى ورقية.",
    "Cairo quarantine administration serves international travelers, pilgrims, and citizens across multiple offices. The public needs trustworthy multilingual information; offices need daily capacity, request tracking, and check-in — without paper chaos.",
  ),
  challenge: L(
    "عمليات حساسة تتقاطع فيها معلومات عامة، بيانات شخصية، سعة مكاتب، وصلاحيات موظفين. التنسيق اليدوي يضعف السجل، ويخلط أدوار السوبر أدمن ومكتب المطار ومكتب المدينة، ويجعل الحجز والشكاوى غير قابلة للتتبع الموحّد.",
    "Sensitive operations mix public guidance, personal data, office capacity, and staff permissions. Manual coordination weakens the record, blurs super-admin vs airport vs city-office roles, and leaves booking and complaints without a unified trail.",
  ),
  thinking: L(
    "هذا ليس موقعًا تعريفيًا فقط — هو نظام حالات: حالة مسافر، مكتب، سعة يوم، طلب، بطاقة QR، شكوى، وصلاحية. الواجهة العامة تبني الثقة؛ لوحة الإدارة تحمي السجل؛ القواعد (توقيت القاهرة، حد يومي، أدوار) تُفرض في الخادم لا في الواجهة وحدها.",
    "This is not only an informational site — it is a case system: traveler state, office, daily capacity, request, QR card, complaint, and permission. The public UI builds trust; the admin console protects the record; rules (Cairo time, daily caps, roles) are enforced on the server — not only in the UI.",
  ),
  solution: L(
    "بوابة عامة متعددة اللغات (عربي/إنجليزي/صيني/فرنسي) مع حجز موحّد وبطاقة QR، وشكاوى مربوطة بالمكاتب، ولوحة إدارة لإحصاءات الطلبات والكتالوجات والمستخدمين — فوق Firestore وقواعد وصول ومسارات API محمية بمعدّل طلبات.",
    "A multilingual public portal (AR/EN/ZH/FR) with unified booking and QR cards, office-linked complaints, and an admin console for request stats, catalogs, and users — on Firestore, access rules, and rate-limited protected API routes.",
  ),
  impact: L(
    "من تنسيق يدوي وصلاحيات ضبابية إلى تشغيل حالات حساس بسجل أوضح وحوكمة أدوار على مستوى المكتب.",
    "From manual coordination and blurry permissions to sensitive case operations with a clearer record and office-level role governance.",
  ),
  behindInterface: behind(
    "المسافر يؤكد حجز موعد تطعيم",
    "Traveler confirms a vaccination appointment",
    [
      [
        "اختيار حالة المسافر والمكتب النشط الذي يخدمها",
        "Traveler state and an active office that serves it are selected",
      ],
      [
        "التحقق من قواعد التاريخ بتوقيت القاهرة وحد السعة اليومية",
        "Date rules in Africa/Cairo time and daily capacity are checked",
      ],
      [
        "كتابة الطلب في المخزن مع رقم فريد",
        "Request is written to the store with a unique number",
      ],
      [
        "إصدار بطاقة QR ورابط طلباتي",
        "QR card and My Requests link are issued",
      ],
      [
        "ظهور الطلب في لوحة المكتب حسب الصلاحية فقط",
        "Request appears in the office console by permission only",
      ],
    ],
    "الضغطة العامة تخلق سجلًا تشغيليًا محكومًا — لا مجرد رسالة نجاح.",
    "The public tap creates a governed ops record — not just a success message.",
  ),
  techRationale: [
    techWhy(
      "تعدد اللغات واتجاه النص جزء من الخدمة لا من التجميل.",
      "Multilingual layout is part of the service, not decoration.",
      "المسافر الدولي والحاج يحتاجان نفس المسار بمحتوى واتجاه صحيح؛ الحجز والبطاقة يترجمان مع الرابط.",
      "International travelers and pilgrims need the same path with correct copy and direction; booking and card follow the locale in the URL.",
      ["Next.js App Router locales", "RTL/LTR"],
    ),
    techWhy(
      "قواعد السعة والصلاحيات تُفرض في الخادم والمخزن.",
      "Capacity and permission rules are enforced in server and store.",
      "حد الحجز اليومي وأدوار المكتب لا تُترك لواجهة فقط — مسارات API وقواعد Firestore تحمي السجل الحساس.",
      "Daily booking caps and office roles are not UI-only — API routes and Firestore rules protect the sensitive record.",
      ["Firestore rules", "Admin SDK", "Rate limiting"],
    ),
    techWhy(
      "فصل المحتوى الإرشادي عن مسار الحجز التشغيلي.",
      "Separate guidance content from the operational booking path.",
      "صفحات الفئات تعلّم؛ مسار الحجز ينفّذ — حتى لا تتكرر نماذج وتتضارب السعة.",
      "Category pages inform; the booking path executes — so forms do not duplicate and capacity does not conflict.",
      ["Unified booking flow", "Catalog-driven traveler states"],
    ),
  ],
  sector: "services",
  systemType: "operations",
  status: "deployed",
  featured: false,
  region: ["Egypt"],
  roles: [
    role(
      "traveler",
      "مسافر / مواطن",
      "Traveler / citizen",
      "معلومات موثوقة وحجز واضح دون مراجعة مكتب أولًا.",
      "Trusted information and clear booking without visiting an office first.",
      "صفحات إرشادية، حجز، بطاقة QR، وطلباتي.",
      "Guidance pages, booking, QR card, and My Requests.",
      "حجز موعد، تحميل البطاقة، وتقديم شكوى أو مقترح.",
      "Book an appointment, download the card, and submit a complaint or suggestion.",
      ["guidance", "booking", "qr-pass", "complaints"],
      ["booking", "complaint"],
    ),
    role(
      "office-user",
      "مستخدم مكتب",
      "Office user",
      "تنفيذ حضور اليوم على الطلبات الظاهرة لمكتبه.",
      "Run today’s check-in on requests visible to their office.",
      "طابور اليوم وبطاقات QR الواردة لمكتبه فقط.",
      "Today’s queue and inbound QR cards for their office only.",
      "تسجيل حضور ومتابعة حالة الطلب ضمن المكتب.",
      "Check in and update request state within the office.",
      ["queue", "cases", "qr-pass"],
      ["checkin"],
    ),
    role(
      "office-admin",
      "أدمن مكتب",
      "Office admin",
      "إدارة سعة المكتب وإغلاق الطابور ومتابعة الشكاوى.",
      "Manage office capacity, close the queue, and follow complaints.",
      "إحصاءات المكتب، السعة اليومية، والشكاوى المرتبطة.",
      "Office stats, daily capacity, and linked complaints.",
      "ضبط السعة، إغلاق الطابور، ومعالجة الاستثناءات المحلية.",
      "Set capacity, close the queue, and handle local exceptions.",
      ["queue", "cases", "complaints", "catalogs"],
      ["checkin", "complaint"],
    ),
    role(
      "specialist",
      "مختص تشغيلي",
      "Ops specialist",
      "متابعة حالات عبر مكاتب عند التصعيد.",
      "Follow cases across offices when escalated.",
      "طلبات متقدمة وتقارير تشغيلية محدودة.",
      "Escalated requests and limited operational reports.",
      "مراجعة ومعالجة مسارات الاستثناء.",
      "Review and process exception paths.",
      ["cases", "complaints"],
      ["booking", "complaint"],
    ),
    role(
      "admin",
      "سوبر أدمن",
      "Super admin",
      "حوكمة المستخدمين والكتالوجات والإعدادات العامة.",
      "Govern users, catalogs, and global settings.",
      "كل المكاتب، المستخدمون، اللقاحات، وحالات المسافر، وإعدادات التطبيق.",
      "All offices, users, vaccines, traveler states, and app settings.",
      "إنشاء ملفات أدمن، بذر كتالوجات، وأرشفة وصيانة.",
      "Create admin profiles, seed catalogs, and run retention/maintenance.",
      ["catalogs", "cases", "queue", "permissions"],
      ["booking", "checkin", "complaint", "governance"],
    ),
    role(
      "permissions",
      "حوكمة الوصول",
      "Access governance",
      "فصل صارم بين العام والمكتب والسوبر أدمن.",
      "Strict separation of public, office, and super-admin access.",
      "قواعد المخزن ومسارات الإدارة المحمية.",
      "Store rules and protected admin routes.",
      "فرض أقل صلاحية ممكنة على كل سجل.",
      "Enforce least privilege on every record.",
      ["permissions", "cases"],
      ["governance"],
    ),
  ],
  modules: [
    mod(
      "guidance",
      "المحتوى الإرشادي",
      "Guidance content",
      "صفحات مسافر دولي وحج وعمرة وخدمات مواطن وميثاق.",
      "International traveler, Hajj/Umrah, citizen services, and charter pages.",
      "معلومات متفرقة وغير متعددة اللغات.",
      "Scattered, non-multilingual information.",
      "محتوى محلي الاتجاه مع بطاقات خدمات وروابط رسمية.",
      "Locale-aware content with service cards and official links.",
      "يمهّد لمسار الحجز دون تكرار النماذج.",
      "Leads into booking without duplicating forms.",
    ),
    mod(
      "booking",
      "حجز المواعيد",
      "Appointment booking",
      "مسار موحّد: حالة مسافر ثم مكتب ثم تاريخ ثم تأكيد.",
      "Unified path: traveler state, office, date, then confirm.",
      "حجز غير منضبط بالسعة أو بتوقيت القاهرة.",
      "Booking unconstrained by capacity or Cairo time.",
      "قواعد تاريخ وسعة تُتحقق عبر API قبل الكتابة.",
      "Date and capacity rules validated via API before write.",
      "ينتج طلبًا وبطاقة ويغذي لوحة المكتب.",
      "Produces a request and card and feeds the office console.",
    ),
    mod(
      "qr-pass",
      "بطاقة QR",
      "QR pass",
      "بطاقة رقمية للعرض عند المكتب مع تحميل ومشاركة.",
      "Digital card for office presentation with download and share.",
      "إثبات موعد ورقي سهل الفقد أو الالتباس.",
      "Paper proof that is easy to lose or confuse.",
      "رمز وبطاقة مترجمة حسب لغة الرابط.",
      "Code and card localized to the URL language.",
      "يربط الحجز بتسجيل الحضور.",
      "Binds booking to check-in.",
    ),
    mod(
      "queue",
      "الطابور اليومي",
      "Daily queue",
      "سعة المكتب، إغلاق اليوم، وإشعارات الانتظار عند التفعيل.",
      "Office capacity, day close, and optional waiting notifications.",
      "طابور غير مرئي أو بلا حد يومي موثوق.",
      "An invisible queue or an unreliable daily cap.",
      "عدّ يومي وقواعد مكتب (بما فيها تشغيل ممتد لمكتب المطار عند الحاجة).",
      "Daily counts and office rules (including extended airport hours when needed).",
      "يحمي الحجز من تجاوز السعة ويمنح المكتب أداة إغلاق.",
      "Protects booking from over-cap and gives the office a close tool.",
    ),
    mod(
      "cases",
      "إدارة الطلبات",
      "Request / case management",
      "تتبع الحجوزات والشكاوى كسجلات تشغيلية.",
      "Track bookings and complaints as operational records.",
      "حالات بلا مالك مكتب أو بلا أثر زمني.",
      "Cases with no office owner or time trail.",
      "سجل طلبات مع فلترة بالمكتب والحالة والصلاحية.",
      "Request ledger filtered by office, state, and permission.",
      "يغذي الإحصاءات والحوكمة.",
      "Feeds stats and governance.",
    ),
    mod(
      "complaints",
      "الشكاوى والمقترحات",
      "Complaints & suggestions",
      "نماذج مربوطة بمكتب محدد مع قناة واتساب اختيارية.",
      "Forms bound to a specific office with optional WhatsApp channel.",
      "ملاحظات عامة لا تصل للجهة الصحيحة.",
      "General feedback that never reaches the right desk.",
      "توجيه حسب المكتب داخل السجل التشغيلي.",
      "Office-routed intake inside the ops ledger.",
      "يتكامل مع لوحة الأدمن ومتابعة المختص.",
      "Integrates with the admin console and specialist follow-up.",
    ),
    mod(
      "catalogs",
      "الكتالوجات التشغيلية",
      "Operational catalogs",
      "مكاتب، لقاحات وأسعار، وحالات مسافر قابلة للتعديل.",
      "Offices, vaccines and prices, and editable traveler states.",
      "قوائم ثابتة في الكود يصعب تحديثها تشغيليًا.",
      "Hard-coded lists that ops cannot update.",
      "مجموعات Firestore تُبذر وتُدار من لوحة السوبر أدمن.",
      "Firestore collections seeded and managed from the super-admin console.",
      "يقود فلترة المكاتب وقواعد الحجز والمحتوى السعري.",
      "Drives office filtering, booking rules, and price content.",
    ),
    mod(
      "permissions",
      "الصلاحيات",
      "Permissions",
      "أدوار سوبر أدمن وأدمن مكتب ومستخدم مكتب على سجلات حساسة.",
      "Super-admin, office-admin, and office-user roles on sensitive records.",
      "وصول أعرض من اللازم لبيانات المسافرين.",
      "Broader-than-needed access to traveler data.",
      "قواعد مخزن ومسارات إدارة مع أقل صلاحية.",
      "Store rules and admin routes with least privilege.",
      "يحمي كل الوحدات ويفصل العام عن التشغيلي.",
      "Protects every module and separates public from operational access.",
    ),
  ],
  workflows: [
    wf(
      "booking",
      "الحجز",
      "Booking",
      [
        ["حالة مسافر", "Traveler state"],
        ["مكتب", "Office"],
        ["تاريخ", "Date"],
        ["تأكيد وQR", "Confirm & QR"],
      ],
      "customer",
    ),
    wf(
      "checkin",
      "تسجيل الحضور",
      "Check-in",
      [
        ["عرض البطاقة", "Present card"],
        ["تحقق المكتب", "Office verify"],
        ["تسجيل حضور", "Check in"],
        ["إغلاق حالة اليوم", "Close day state"],
      ],
      "operations",
    ),
    wf(
      "complaint",
      "الشكوى",
      "Complaint",
      [
        ["اختيار مكتب", "Select office"],
        ["إرسال", "Submit"],
        ["توجيه", "Route"],
        ["معالجة", "Handle"],
      ],
      "exceptions",
    ),
    wf(
      "governance",
      "الحوكمة",
      "Governance",
      [
        ["ضبط كتالوج", "Configure catalog"],
        ["ضبط سعة", "Set capacity"],
        ["مراجعة صلاحيات", "Review permissions"],
        ["صيانة وأرشفة", "Maintenance & retention"],
      ],
      "management",
    ),
  ],
  integrations: [
    integ(
      "firebase",
      "منصة بيانات",
      "Data platform",
      "Firebase Auth / Firestore",
      "هوية الإدارة وسجلات الطلبات والكتالوجات",
      "Admin identity plus request and catalog records",
    ),
    integ(
      "whatsapp",
      "رسائل",
      "Messaging",
      "WhatsApp complaints line",
      "قناة شكاوى واقتراحات اختيارية للجمهور",
      "Optional public complaints and suggestions channel",
    ),
    integ(
      "push",
      "إشعارات",
      "Notifications",
      "Web Push (optional)",
      "تنبيهات انتظار الطابور عند التفعيل",
      "Queue waiting alerts when enabled",
    ),
  ],
  stack: [
    {
      layer: "interface",
      items: ["Next.js", "Multilingual RTL/LTR", "PWA", "Admin console"],
      responsibility: L(
        "ثقة عامة وتشغيل مكتبي منفصل بالصلاحية.",
        "Public trust and permission-separated office ops.",
      ),
    },
    {
      layer: "application",
      items: ["Booking APIs", "Availability checks", "Rate limiting"],
      responsibility: L(
        "فرض السعة والقواعد قبل الكتابة.",
        "Enforce capacity and rules before write.",
      ),
    },
    {
      layer: "data",
      items: ["Firestore", "Firebase Auth", "Seeded catalogs", "Audit-friendly records"],
    },
    {
      layer: "business",
      items: ["Cairo timezone rules", "Daily caps", "Office-scoped RBAC"],
      responsibility: L(
        "قواعد الحالات الحساسة فوق الواجهة.",
        "Sensitive-case rules above the interface.",
      ),
    },
    {
      layer: "deployment",
      items: ["Firebase rules/indexes", "Env separation", "Ops runbooks"],
    },
  ],
  mass: { ...mass },
  capabilities: [
    "product",
    "ux",
    "frontend",
    "backend",
    "data",
    "integrations",
    "operations",
  ],
  outcomes: [
    {
      from: L("تنسيق يدوي بين المكاتب", "Manual coordination across offices"),
      to: L("سجل طلبات محكوم بالمكتب", "Office-governed request ledger"),
    },
    {
      from: L("معلومات أحادية اللغة", "Single-language information"),
      to: L("مسار متعدد اللغات بنفس القواعد", "Multilingual path with the same rules"),
    },
    {
      from: L("حجز بلا سعة موثوقة", "Booking without trustworthy capacity"),
      to: L("حد يومي وتحقق بتوقيت القاهرة", "Daily cap with Cairo-time validation"),
    },
    {
      from: L("صلاحيات عريضة على بيانات حساسة", "Broad access to sensitive data"),
      to: L("أدوار مكتب بأقل صلاحية", "Office roles with least privilege"),
    },
  ],
  arkanScope: [
    L("نمذجة الحالات الحساسة والصلاحيات", "Sensitive-case and permission modeling"),
    L("تجربة عامة متعددة اللغات", "Multilingual public experience"),
    L("مسار حجز وبطاقة QR", "Booking path and QR card"),
    L("لوحة تشغيل للمكاتب", "Office operations console"),
    L("قواعد بيانات وAPI محمية", "Protected data rules and APIs"),
    L("كتالوجات وتشغيل يومي", "Catalogs and daily operations"),
  ],
  relatedProjects: ["nexora-erp", "rentara"],
  scale: scaleFromMass(mass, 4),
  dna: ["ops", "gov", "rbac", "multilingual", "queue"],
  atlas: { x: 65, y: 72 },
};
