import type { Project } from "../types";
import {
  L,
  behind,
  integ,
  mod,
  role,
  scaleFromMass,
  techWhy,
  wf,
} from "../projectBuilders";

const mass = {
  modules: 8,
  roles: 6,
  workflows: 4,
  interfaces: 4,
  integrations: 3,
  automations: 2,
  dataDomains: 5,
  locations: 1,
} as const;

export const hakimoProduction: Project = {
  id: "HKM-01",
  slug: "hakimo-production",
  title: L("Hakimo Production", "Hakimo Production"),
  descriptor: L("تشغيل خطوط إنتاج", "Production line operations"),
  summary: L(
    "نظام تشغيل صناعي يربط خطوط الإنتاج والتقارير اليومية والصلاحيات والمؤشرات في سطح واحد للمشغّلين والمشرفين والإدارة.",
    "An industrial operations system that connects production lines, daily reports, permissions, and KPIs in one surface for operators, supervisors, and management.",
  ),
  context: L(
    "مصنع متعدد الخطوط يحتاج رؤية لحظية لحالة الإنتاج، وإدخالًا سريعًا من الصالة، وتقارير يومية قابلة للطباعة والمشاركة، دون الاعتماد على جداول متفرقة أو رسائل واتساب غير متتبعة.",
    "A multi-line factory needs live line visibility, fast floor entry, and daily reports that can be printed and shared — without scattered spreadsheets or untracked WhatsApp messages.",
  ),
  challenge: L(
    "التتبع اليدوي يفصل حالة الخط عن التقرير عن المخزون عن الموارد البشرية. المشرف يدخل بيانات بعد انتهاء الوردية، والإدارة ترى صورة متأخرة، والصلاحيات غير دقيقة بين المشغّل ومشرف الصالة ومدير المصنع.",
    "Manual tracking splits line state, reporting, inventory, and HR. Supervisors enter data after the shift ends, management sees a delayed picture, and permissions blur between operator, hall supervisor, and factory manager.",
  ),
  thinking: L(
    "المشكلة ليست «لوحة أجمل» — بل نظام تشغيل يلتزم بدورة الوردية: من حالة الخط، إلى الإدخال السريع، إلى التقرير، إلى المؤشر، مع RBAC يحدد من يرى وماذا يفعل. الواجهة يجب أن تكون سريعة على أرض المصنع، والطبقة الخلفية تحفظ أثر كل عملية.",
    "The problem is not a prettier dashboard — it is an operating system that respects the shift cycle: line state → quick entry → report → KPI, with RBAC deciding who sees and who acts. The UI must be fast on the factory floor; the backend must keep an audit trail for every action.",
  ),
  solution: L(
    "منصة تشغيل إنتاجية: خطوط بحالة لحظية، منتجات ومخزون، تقارير يومية مع طباعة وتصدير، إدخال سريع للمشرفين، لوحات مؤشرات حسب الدور، ووحدة موارد بشرية وموافقات مربوطة بنفس الهوية والصلاحيات.",
    "A production operations platform: live line states, products and stock, daily reports with print/export, quick-entry for supervisors, role-specific KPI boards, and HR/approvals bound to the same identity and permissions model.",
  ),
  impact: L(
    "من تتبع متأخر ومتفرق إلى تشغيل مرئي قابل للحوكمة داخل وردية العمل نفسها.",
    "From delayed, fragmented tracking to visible, governable operations inside the same working shift.",
  ),
  behindInterface: behind(
    "المشرف يحفظ تقرير إنتاج من الإدخال السريع",
    "Supervisor saves a production report from quick entry",
    [
      [
        "التحقق من الجلسة والدور والصلاحية reports.create",
        "Session, role, and reports.create permission are checked",
      ],
      [
        "ربط التقرير بالخط والوردية والمنتج والكميات",
        "Report is bound to line, shift, product, and quantities",
      ],
      [
        "تحديث حالة الخط ومجاميع اليوم في مخزن التشغيل",
        "Line state and daily totals update in the ops store",
      ],
      [
        "كتابة سجل نشاط قابل للتدقيق",
        "An auditable activity record is written",
      ],
      [
        "تجهيز مسار طباعة / PDF / مشاركة واتساب",
        "Print / PDF / WhatsApp share path is prepared",
      ],
    ],
    "ضغطة واحدة على الصالة تُغلق حلقة التقرير والحوكمة معًا.",
    "One floor action closes both the report loop and the governance loop.",
  ),
  techRationale: [
    techWhy(
      "واجهة سريعة للمصنع قبل أناقة لوحة تنفيذية.",
      "Factory-floor speed before executive polish.",
      "المشرف يحتاج إدخالًا وحفظًا وطباعة في ثوانٍ — لذلك أولوية التجربة للمسارات القصيرة والصلاحيات الظاهرة، لا للرسوم البيانية الثقيلة أولًا.",
      "Supervisors need enter → save → print in seconds — so short paths and visible permissions come before heavy charts.",
      ["React", "Zustand", "Permission-first UI"],
    ),
    techWhy(
      "هوية وصلاحيات ديناميكية بدل أدوار ثابتة في الكود.",
      "Dynamic identity and permissions instead of hard-coded roles.",
      "خطوط الإنتاج تتغير وأدوار الصالة تتوسع — RBAC المخزّن يسمح بإنشاء أدوار دون إعادة نشر الواجهة.",
      "Lines change and floor roles expand — stored RBAC lets new roles appear without redeploying the UI.",
      ["Firebase Auth", "Firestore RBAC"],
    ),
    techWhy(
      "فصل طبقات العرض عن منطق التشغيل عن الوصول للبيانات.",
      "Separate presentation, ops logic, and data access.",
      "حتى يبقى النظام قابلًا لإضافة وحدات (جودة، تكاليف، موارد بشرية) دون كسر مسارات الإنتاج الأساسية.",
      "So quality, costs, and HR modules can grow without breaking core production paths.",
      ["Feature modules", "Service layer", "Typed domain models"],
    ),
  ],
  sector: "operations",
  systemType: "operations",
  status: "evolving",
  featured: true,
  region: ["Egypt"],
  roles: [
    role(
      "operator",
      "مشغّل",
      "Operator",
      "إدخال حالة العمل اليومية بسرعة دون تعقيد إداري.",
      "Enter daily work state quickly without administrative friction.",
      "خطه، مهامه، ونماذج الإدخال المتاحة لدوره.",
      "Their line, tasks, and entry forms allowed for their role.",
      "تسجيل إنتاج ضمن صلاحياته ومشاركة التقرير مع المشرف.",
      "Log production within permissions and share the report with a supervisor.",
      ["lines", "quick-entry", "reports"],
      ["shift-report"],
    ),
    role(
      "supervisor",
      "مشرف",
      "Supervisor",
      "إغلاق وردية بتقرير مكتمل وقابل للطباعة.",
      "Close a shift with a complete, printable report.",
      "تقارير اليوم، حالة الخطوط المسندة، ومسارات الإدخال السريع.",
      "Today’s reports, assigned line states, and quick-entry paths.",
      "إنشاء تقارير، طباعة/تصدير، ومشاركة واتساب.",
      "Create reports, print/export, and share via WhatsApp.",
      ["quick-entry", "reports", "lines"],
      ["shift-report", "handover"],
    ),
    role(
      "hall-supervisor",
      "مشرف صالة",
      "Hall supervisor",
      "تصحيح حالة الخط وتعديل التقارير قبل أن تصل للإدارة.",
      "Correct line state and edit reports before they reach management.",
      "كل خطوط الصالة، التعديلات المعلقة، وصورة أوسع من المشرف الفردي.",
      "All hall lines, pending edits, and a wider view than a single supervisor.",
      "تعديل التقارير وحالات الخطوط وعرض الصفحات التشغيلية.",
      "Edit reports and line states; view operational pages.",
      ["lines", "reports", "products", "kpi"],
      ["shift-report", "line-control"],
    ),
    role(
      "factory-manager",
      "مسؤول مصنع",
      "Factory manager",
      "رؤية شاملة للأداء دون كسر سلامة البيانات.",
      "Full performance visibility without breaking data integrity.",
      "لوحات المؤشرات، ملخص الخطوط، وتقارير قابلة للطباعة فقط.",
      "KPI boards, line summaries, and print-only report access.",
      "المراجعة والتصدير والطباعة — بدون إنشاء أو حذف تشغيلي.",
      "Review, export, and print — without operational create/delete.",
      ["kpi", "reports", "lines"],
      ["management-review"],
    ),
    role(
      "hr",
      "موارد بشرية",
      "HR",
      "ربط الحضور والإجازات والسلف بنفس هوية المصنع.",
      "Tie attendance, leave, and advances to the same factory identity.",
      "طلبات الموظفين وسلاسل الموافقات.",
      "Employee requests and approval chains.",
      "تشغيل مسارات الموارد البشرية والموافقات المؤسسية.",
      "Run HR paths and institutional approvals.",
      ["hr", "approvals"],
      ["approvals"],
    ),
    role(
      "admin",
      "مدير النظام",
      "System admin",
      "حوكمة المستخدمين والأدوار وسجل النشاط.",
      "Govern users, roles, and the activity log.",
      "المستخدمون، الأدوار الديناميكية، والتدقيق الكامل.",
      "Users, dynamic roles, and full audit.",
      "إنشاء حسابات، ضبط صلاحيات، وحذف تقارير عند الحاجة.",
      "Create accounts, configure permissions, and delete reports when required.",
      ["system", "kpi", "reports", "hr"],
      ["management-review", "approvals"],
    ),
  ],
  modules: [
    mod(
      "lines",
      "خطوط الإنتاج",
      "Production lines",
      "إدارة ومتابعة خطوط متعددة بحالة لحظية.",
      "Manage and monitor multiple lines with live state.",
      "غياب صورة موحّدة لحالة الخط أثناء الوردية.",
      "No shared picture of line state during the shift.",
      "سجل خط + حالة + ربط بالتقارير والمنتجات.",
      "Line registry + state + binding to reports and products.",
      "يربط الإدخال السريع والتقارير ولوحات المؤشرات.",
      "Connects quick entry, reports, and KPI boards.",
    ),
    mod(
      "products",
      "المنتجات والمخزون",
      "Products & stock",
      "كتالوج منتجات مع أرصدة وربط بتقارير الإنتاج.",
      "Product catalog with balances tied to production reports.",
      "فصل بين ما يُنتج وما يُحسب في المخزون.",
      "Split between what is produced and what stock accounts for.",
      "كيانات منتج مرتبطة بخطوط وتقارير يومية.",
      "Product entities linked to lines and daily reports.",
      "يغذي التقارير والمؤشرات وتخطيط الإنتاج.",
      "Feeds reports, KPIs, and production planning.",
    ),
    mod(
      "reports",
      "التقارير اليومية",
      "Daily reports",
      "تسجيل إنتاج يومي مع طباعة وتصدير ومشاركة.",
      "Daily production logging with print, export, and share.",
      "تقارير متأخرة أو ضائعة بين الورق والواتساب.",
      "Late or lost reports between paper and WhatsApp.",
      "نماذج منظمة + مرفقات أثر + مسارات مشاركة.",
      "Structured forms + audit trail + share paths.",
      "يغلق حلقة الوردية ويمدّ الإدارة بأرقام موثوقة.",
      "Closes the shift loop and gives management trusted numbers.",
    ),
    mod(
      "quick-entry",
      "الإدخال السريع",
      "Quick entry",
      "مسار مشرف: إدخال → حفظ → طباعة → واتساب.",
      "Supervisor path: enter → save → print → WhatsApp.",
      "بطء النماذج الكاملة على أرض الصالة.",
      "Full forms are too slow on the floor.",
      "فورم مختصر مربوط بصلاحيات المشرف والخط.",
      "A short form bound to supervisor permissions and line.",
      "يكتب مباشرة في التقارير ويحدّث حالة الخط.",
      "Writes straight into reports and updates line state.",
    ),
    mod(
      "kpi",
      "لوحات المؤشرات",
      "KPI dashboards",
      "رؤية تحليلية حسب الدور: خط، صالة، مصنع.",
      "Role-aware analytics: line, hall, factory.",
      "مؤشرات مشتتة لا تعكس الوردية الحالية.",
      "Scattered metrics that miss the current shift.",
      "تجميع من التقارير وحالات الخطوط في لوحات مفصولة بالصلاحية.",
      "Aggregation from reports and line states into permission-scoped boards.",
      "يخدم الإدارة دون منحها صلاحية تعديل تشغيلي غير لازمة.",
      "Serves management without unnecessary write access.",
    ),
    mod(
      "hr",
      "الموارد البشرية",
      "HR",
      "حضور، إجازات، سلف، رواتب، وهيكل تنظيمي.",
      "Attendance, leave, advances, payroll, org structure.",
      "تشغيل أفراد منفصل عن تشغيل الإنتاج.",
      "People ops disconnected from production ops.",
      "وحدة موارد بشرية على نفس الهوية والصلاحيات.",
      "HR unit on the same identity and permissions fabric.",
      "يتصل بمحرك الموافقات وسجل النشاط.",
      "Connects to approvals and the activity log.",
    ),
    mod(
      "approvals",
      "محرك الموافقات",
      "Approvals engine",
      "سلاسل موافقة وتفويض وتصعيد.",
      "Approval chains, delegation, and escalation.",
      "قرارات معلقة بدون مسار واضح.",
      "Stuck decisions with no clear path.",
      "قواعد سلسلة مرتبطة بالأدوار والطلبات.",
      "Chain rules bound to roles and request types.",
      "يربط الموارد البشرية والطلبات الإدارية بالحوكمة.",
      "Binds HR and admin requests to governance.",
    ),
    mod(
      "system",
      "النظام والصلاحيات",
      "System & permissions",
      "مستخدمون، أدوار ديناميكية، وسجل نشاط.",
      "Users, dynamic roles, and activity log.",
      "حسابات وصلاحيات غير قابلة للتدقيق.",
      "Accounts and permissions that cannot be audited.",
      "RBAC مخزّن + تدقيق على الإنشاء والتعديل والحذف.",
      "Stored RBAC + audit on create, update, and delete.",
      "يحمي كل الوحدات ويحدد ما يظهر لكل دور.",
      "Protects every module and decides what each role sees.",
    ),
  ],
  workflows: [
    wf(
      "shift-report",
      "تقرير الوردية",
      "Shift report",
      [
        ["فتح وردية / خط", "Open shift / line"],
        ["إدخال سريع", "Quick entry"],
        ["حفظ تقرير", "Save report"],
        ["طباعة أو مشاركة", "Print or share"],
      ],
      "operations",
    ),
    wf(
      "line-control",
      "ضبط الخط",
      "Line control",
      [
        ["مراجعة الحالة", "Review state"],
        ["تعديل حالة الخط", "Update line state"],
        ["تصحيح تقرير", "Correct report"],
        ["تأكيد للصالة", "Confirm for hall"],
      ],
      "operations",
    ),
    wf(
      "management-review",
      "مراجعة الإدارة",
      "Management review",
      [
        ["تجميع اليوم", "Aggregate day"],
        ["لوحة مؤشرات", "KPI board"],
        ["تصدير", "Export"],
        ["قرار تشغيلي", "Ops decision"],
      ],
      "management",
    ),
    wf(
      "approvals",
      "الموافقات",
      "Approvals",
      [
        ["طلب", "Request"],
        ["سلسلة موافقة", "Approval chain"],
        ["تفويض أو تصعيد", "Delegate or escalate"],
        ["إغلاق", "Close"],
      ],
      "exceptions",
    ),
  ],
  integrations: [
    integ(
      "firebase",
      "منصة بيانات",
      "Data platform",
      "Firebase Auth / Firestore / Storage",
      "هوية، سجلات تشغيل، وملفات تقارير",
      "Identity, operational records, and report files",
    ),
    integ(
      "export",
      "تصدير",
      "Export",
      "Excel / PDF / Print",
      "مخرجات وردية قابلة للأرشفة والمشاركة",
      "Shift outputs ready to archive and share",
    ),
    integ(
      "whatsapp",
      "رسائل",
      "Messaging",
      "WhatsApp share",
      "مشاركة تقرير بعد الحفظ مباشرة من الصالة",
      "Share a report immediately after save from the floor",
    ),
  ],
  stack: [
    {
      layer: "interface",
      items: ["React 19", "Vite", "Role-aware dashboards", "RTL ops UI"],
      responsibility: L(
        "أسطح سريعة للصالة ولوحات حسب الدور.",
        "Fast floor surfaces and role-scoped boards.",
      ),
    },
    {
      layer: "application",
      items: ["Zustand", "Feature modules", "Permission guards"],
      responsibility: L(
        "تنسيق حالة التشغيل والصلاحيات.",
        "Orchestrate ops state and permissions.",
      ),
    },
    {
      layer: "data",
      items: ["Firestore", "Firebase Auth", "Storage", "Activity log"],
      responsibility: L(
        "سجلات إنتاج وتدقيق ومستندات.",
        "Production records, audit, and documents.",
      ),
    },
    {
      layer: "business",
      items: ["RBAC", "Shift reporting", "Approvals chains"],
      responsibility: L(
        "قواعد المصنع قبل العرض.",
        "Factory rules before presentation.",
      ),
    },
    {
      layer: "deployment",
      items: ["SPA hosting", "Firebase project environments"],
    },
  ],
  mass: { ...mass },
  capabilities: [
    "product",
    "frontend",
    "backend",
    "data",
    "operations",
    "integrations",
  ],
  outcomes: [
    {
      from: L("تتبع يدوي متأخر", "Delayed manual tracking"),
      to: L("حالة خط مرئية أثناء الوردية", "Line state visible during the shift"),
    },
    {
      from: L("تقارير واتساب/ورق", "WhatsApp / paper reports"),
      to: L("تقرير منظم قابل للطباعة والتدقيق", "Structured printable, auditable reports"),
    },
    {
      from: L("صلاحيات ضبابية", "Blurry permissions"),
      to: L("RBAC ديناميكي حسب الدور", "Dynamic role-based RBAC"),
    },
    {
      from: L("إنتاج وموارد بشرية منفصلان", "Split production and HR"),
      to: L("هوية وتشغيل موحّدان", "Unified identity and operations"),
    },
  ],
  arkanScope: [
    L("استراتيجية المنتج التشغيلي", "Operational product strategy"),
    L("نمذجة خطوط وتقارير وصلاحيات", "Line, report, and permission modeling"),
    L("واجهات صالة ولوحات مؤشرات", "Floor UI and KPI boards"),
    L("هندسة الواجهة وحالة التطبيق", "Frontend architecture and app state"),
    L("طبقة بيانات وتدقيق", "Data layer and audit"),
    L("مسارات طباعة وتصدير ومشاركة", "Print, export, and share paths"),
    L("تطوير مستمر للوحدات", "Ongoing module evolution"),
  ],
  relatedProjects: ["nexora-erp", "velora-pos"],
  scale: scaleFromMass(mass, 4),
  dna: ["ops", "industrial", "rbac", "kpi", "shift"],
  atlas: { x: 78, y: 58 },
};
