import type { Project } from "../types";
import {
  L,
  behind,
  integ,
  mod,
  role,
  scaleFromMass,
  techWhy,
  wf,
} from "../projectBuilders";

const mass = {
  modules: 8,
  roles: 7,
  workflows: 4,
  interfaces: 4,
  integrations: 4,
  automations: 2,
  dataDomains: 5,
  locations: 2,
} as const;

export const masarValet: Project = {
  id: "MVS-01",
  slug: "masar-valet",
  title: L("مسار", "MASAR"),
  descriptor: L(
    "بنية تشغيل دورة حياة المركبة من الاستقبال حتى التسليم والمحاسبة.",
    "Vehicle lifecycle operations infrastructure from intake through handover and accounting.",
  ),
  summary: L(
    "نظام تشغيل صف سيارات يربط التذكرة العامة، QR/NFC، الفرق الميدانية، الدفع، والمحاسبة عبر مواقع متعددة.",
    "Valet operations system linking public tickets, QR/NFC assets, field teams, payments, and accounting across sites.",
  ),
  context: L(
    "عمليات الضيافة والمولات تحرّك مركبات عبر مواقع وفرق ميدانية وعملاء بزمن تسليم ضيق، غالبًا فوق ورق واتصال هاتفي.",
    "Hospitality and mall ops move vehicles across sites and field teams with tight handover windows—often on paper and phone calls.",
  ),
  challenge: L(
    "التدفق الورقي — تذكرة، بحث يدوي، طلب هاتفي، دفع غير متتبع — يبطئ التسليم ويكسر الرؤية المحاسبية عبر المواقع.",
    "Paper flow—ticket, manual search, phone request, untracked payment—slows handover and breaks multi-site accounting visibility.",
  ),
  thinking: L(
    "المشكلة لم تكن غياب لوحة للسيارات. المشكلة دورة حياة المركبة عبر أشخاص وخطوات بلا مصدر حقيقة واحد.",
    "The problem was not a missing car dashboard. It was a vehicle lifecycle across people and steps without a single source of truth.",
  ),
  solution: L(
    "نظام تشغيلي واحد يربط العميل والفريق والموقع والدفع والمحاسبة عبر تذاكر رقمية وأصول QR/NFC وPWA للفرق الميدانية.",
    "One operating system connecting guest, staff, site, payment, and accounting via digital tickets, QR/NFC assets, and a field-team PWA.",
  ),
  impact: L(
    "من ورق متفرق إلى تشغيل متصل قابل للتتبع عبر المواقع — حالة واحدة للمركبة يراها العميل والفريق والمالية.",
    "From fragmented paper to connected, traceable multi-site ops—one vehicle state shared by guest, staff, and finance.",
  ),
  behindInterface: behind(
    "اطلب مركبتي",
    "Request my vehicle",
    [
      ["طلب", "Request"],
      ["تحقق", "Validation"],
      ["موقع", "Location"],
      ["تعيين", "Assignment"],
      ["حالة", "Status"],
      ["إشعار", "Notification"],
      ["تسليم", "Handover"],
    ],
    "ما تراه زر على الشاشة. ما يحدث نظام تشغيل كامل للمركبة.",
    "What you see is a screen button. What happens is a full vehicle operating system.",
  ),
  techRationale: [
    techWhy(
      "الفرق الميدانية تحتاج واجهة تعمل دون تثبيت تطبيق وبتجربة عربية كاملة.",
      "Field teams need an install-light surface with full Arabic experience.",
      "واجهة PWA/RTL تقلّل احتكاك التشغيل على الأرض.",
      "A PWA/RTL interface cuts friction on the ground.",
      ["TanStack Start", "PWA", "RTL UI"],
    ),
    techWhy(
      "حالة المركبة والدفع والأدوار يجب أن تُفرض من الخادم لا من الشاشة.",
      "Vehicle state, payments, and roles must be enforced server-side—not in the UI.",
      "قاعدة بسياسات وصول وتخزين خاص يحمي البيانات التشغيلية.",
      "A database with access policies and private storage protects operational data.",
      ["Supabase", "RLS", "PostgreSQL", "Signed URLs"],
    ),
    techWhy(
      "الاستقبال اليدوي للبيانات يبطئ الموقع ويفتح أخطاء لوحات.",
      "Manual plate/data entry slows the lane and introduces plate errors.",
      "استخراج منظم من الصورة يقلّل زمن الاستقبال دون استبدال التحقق البشري.",
      "Structured extraction from photos shortens intake without replacing human checks.",
      ["Vision / extraction"],
    ),
    techWhy(
      "التشغيل متعدد المواقع يحتاج حافة قريبة من المستخدم مع نشر بسيط.",
      "Multi-site ops need an edge close to users with simple deploy.",
      undefined,
      undefined,
      ["Cloudflare Workers"],
    ),
  ],
  sector: "mobility",
  systemType: "operations",
  status: "operating",
  featured: true,
  region: ["Egypt", "Saudi Arabia"],
  roles: [
    role(
      "customer",
      "عميل",
      "Customer",
      "طلب المركبة والدفع وتتبع الحالة دون اتصال بالموقع.",
      "Request the vehicle, pay, and track status without calling the site.",
      "تذكرة عامة: الحالة، المبلغ، وزر الطلب.",
      "Public ticket: status, amount, and request action.",
      "يفتح التذكرة، يطلب المركبة، يدفع، ويتابع التسليم.",
      "Opens the ticket, requests the vehicle, pays, and follows handover.",
      ["ticket", "payment"],
      ["arrival", "request"],
    ),
    role(
      "valet",
      "سائق صف",
      "Valet",
      "مهام واضحة: استقبال، ركن، إحضار، تسليم — بدون بحث هاتفي.",
      "Clear tasks: intake, park, retrieve, hand over—without phone hunting.",
      "قائمة مهام ميدانية مرتبطة بموقع المركبة وحالتها.",
      "Field task list bound to vehicle location and state.",
      "ينفّذ الاستقبال والركن والإحضار ويحدّث الحالة من الـPWA.",
      "Runs intake, parking, and retrieval; updates state from the PWA.",
      ["intake", "parking", "dispatch"],
      ["arrival", "request"],
    ),
    role(
      "supervisor",
      "مشرف",
      "Supervisor",
      "توازن الحمل وإعادة التوجيه عند الضغط أو التعطّل.",
      "Balance load and reassign when the lane is under pressure.",
      "طابور الطلبات، التعيينات، والاستثناءات الحية.",
      "Live request queue, assignments, and exceptions.",
      "يعيد التوجيه، يغلق الاستثناءات، ويراقب زمن التسليم.",
      "Reassigns, closes exceptions, and watches handover time.",
      ["ops", "dispatch"],
      ["request", "exceptions"],
    ),
    role(
      "manager",
      "مدير فرع",
      "Branch manager",
      "رؤية تشغيل الفرع: حجم، أزمنة، وثغور الورديات.",
      "Branch ops view: volume, timings, and shift gaps.",
      "لوحة فرع: حالات، فرق، ومؤشرات تشغيلية.",
      "Branch board: states, teams, and operational indicators.",
      "يضبط الورديات ويراجع الأداء اليومي للموقع.",
      "Sets shifts and reviews the site’s daily performance.",
      ["ops"],
      ["management"],
    ),
    role(
      "ops",
      "عمليات",
      "Operations",
      "معايير موحّدة عبر المواقع وتكاملات الإشعارات والدفع.",
      "Shared standards across sites plus notification and payment integrations.",
      "إعداد المواقع، القواعد، والقنوات.",
      "Site config, rules, and channels.",
      "يفعّل المواقع ويضبط التكاملات وقواعد التشغيل.",
      "Activates sites and configures integrations and operating rules.",
      ["ops", "integrations"],
      ["management"],
    ),
    role(
      "finance",
      "مالية",
      "Finance",
      "كل دفعة مربوطة بتذكرة ومطابقة للمحاسبة.",
      "Every payment bound to a ticket and reconcilable in accounting.",
      "معاملات، تسويات، وربط ERP.",
      "Transactions, reconciliations, and ERP linkage.",
      "يطابق الدفعات ويصدّر السجلات المالية.",
      "Reconciles payments and exports financial records.",
      ["payment", "accounting"],
      ["accounting"],
    ),
    role(
      "admin",
      "مسؤول",
      "Admin",
      "تحكم بالأدوار والصلاحيات والأصول الرقمية للمواقع.",
      "Control roles, permissions, and digital site assets.",
      "هوية، صلاحيات، وأصول QR/NFC.",
      "Identity, permissions, and QR/NFC assets.",
      "يدير المستخدمين والأصول وإعداد النظام.",
      "Manages users, assets, and system configuration.",
      ["ops", "integrations"],
      ["management"],
    ),
  ],
  modules: [
    mod(
      "intake",
      "الاستقبال",
      "Intake",
      "التقاط بيانات المركبة والعميل والحالة الابتدائية عند الوصول.",
      "Captures vehicle, guest, and initial state on arrival.",
      "يدخل المركبة إلى النظام بدل ورقة بلا سياق.",
      "Gets the vehicle into the system instead of a context-free stub.",
      "نموذج استقبال + تحقق + إنشاء تذكرة وأصل رقمي.",
      "Intake form + validation + ticket and digital asset creation.",
      "يغذي التذكرة والمواقف والتوجيه.",
      "Feeds ticket, parking, and dispatch.",
    ),
    mod(
      "ticket",
      "التذكرة العامة",
      "Public ticket",
      "واجهة العميل للحالة والدفع والطلب دون تطبيق.",
      "Guest surface for status, payment, and request—no app install.",
      "يعطي العميل قناة رسمية بدل الاتصال العشوائي.",
      "Gives the guest a formal channel instead of ad-hoc calls.",
      "رابط/QR يفتح حالة حية وإجراءات مسموحة حسب القواعد.",
      "Link/QR opens live state and allowed actions per rules.",
      "يرتبط بالدفع والتوجيه والإشعارات.",
      "Connects to payment, dispatch, and notifications.",
    ),
    mod(
      "parking",
      "المواقف",
      "Parking",
      "خريطة مواقع الانتظار وإدارة المساحات.",
      "Parking map and space management.",
      "يمنع فقدان موقع المركبة داخل الساحة.",
      "Stops vehicles from getting lost inside the lot.",
      "تعيين موقع/مساحة وربطه بحالة المركبة.",
      "Assigns location/space bound to vehicle state.",
      "يخدم التوجيه وطلب الإحضار.",
      "Serves dispatch and retrieval.",
    ),
    mod(
      "dispatch",
      "التوجيه",
      "Dispatch",
      "توجيه الطلبات للفريق الميداني حسب الحمل والقرب.",
      "Routes requests to field staff by load and proximity.",
      "يستبدل النداء العشوائي بتعيين قابل للتتبع.",
      "Replaces random calling with traceable assignment.",
      "طابور طلبات، قواعد تعيين، وتحديث حالة.",
      "Request queue, assignment rules, and state updates.",
      "يربط التذكرة بالمهام الميدانية والإشعارات.",
      "Binds the ticket to field tasks and notifications.",
    ),
    mod(
      "payment",
      "الدفع",
      "Payment",
      "تدفق المعاملات مربوط بالتذكرة قبل أو مع التسليم.",
      "Transaction flow bound to the ticket before or with handover.",
      "يمنع تسليمًا بلا أثر مالي واضح.",
      "Prevents handover without a clear financial trail.",
      "بوابة دفع وحالات معاملة مرتبطة بالتذكرة.",
      "Payment gateway and transaction states on the ticket.",
      "يغذي المحاسبة والتقارير.",
      "Feeds accounting and reporting.",
    ),
    mod(
      "ops",
      "منصة التشغيل",
      "Ops platform",
      "لوحة المواقع والفرق والحالات والاستثناءات.",
      "Control surface for sites, teams, states, and exceptions.",
      "يمنح المشرفين والمديرين رؤية تشغيلية واحدة.",
      "Gives supervisors and managers one operational view.",
      "لوحات حية، ورديات، وإعداد مواقع.",
      "Live boards, shifts, and site configuration.",
      "مركز التحكم لكل الوحدات التشغيلية.",
      "Control hub for all operational modules.",
    ),
    mod(
      "accounting",
      "المحاسبة",
      "Accounting",
      "تسجيل مالي ومطابقة وربط ERP.",
      "Financial records, reconciliation, and ERP linkage.",
      "يغلق الفجوة بين الدفع الميداني والسجل المالي.",
      "Closes the gap between field payment and the ledger.",
      "تصدير/مزامنة فواتير وتسويات حسب التذكرة.",
      "Invoice/sync and reconciliation by ticket.",
      "يرتبط بالدفع وOdoo.",
      "Links to payment and Odoo.",
    ),
    mod(
      "ai-intake",
      "استخراج ذكي",
      "AI intake",
      "استخراج بيانات المركبة من الصور إلى حقول منظمة.",
      "Structured vehicle fields from intake photos.",
      "يقلّل زمن وخطأ إدخال اللوحة والبيانات عند الاستقبال.",
      "Cuts plate/data entry time and error at the lane.",
      "رؤية حاسوبية → اقتراح حقول → تأكيد بشري.",
      "Computer vision → field suggestions → human confirm.",
      "يخدم وحدة الاستقبال فقط كمساعد لا كمصدر حقيقة وحيد.",
      "Serves intake as an assistant—not the sole source of truth.",
    ),
  ],
  workflows: [
    wf(
      "arrival",
      "الوصول",
      "Arrival",
      [
        ["وصول", "Arrival"],
        ["استقبال", "Intake"],
        ["تحقق", "Validation"],
        ["تذكرة", "Ticket"],
        ["ركن", "Park"],
      ],
      "customer",
    ),
    wf(
      "request",
      "طلب المركبة",
      "Vehicle request",
      [
        ["طلب", "Request"],
        ["تحقق", "Validate"],
        ["توجيه", "Dispatch"],
        ["دفع", "Payment"],
        ["تسليم", "Handover"],
      ],
      "operations",
    ),
    wf(
      "accounting",
      "المحاسبة",
      "Accounting",
      [
        ["معاملة", "Transaction"],
        ["مطابقة", "Reconciliation"],
        ["سجل ERP", "ERP record"],
      ],
      "finance",
    ),
    wf(
      "exceptions",
      "الاستثناءات",
      "Exceptions",
      [
        ["تعطّل", "Blocked"],
        ["إعادة توجيه", "Reassign"],
        ["إغلاق", "Close"],
      ],
      "exceptions",
    ),
  ],
  integrations: [
    integ("odoo", "محاسبة", "Accounting", "Odoo", "فواتير ومطابقة وسجلات مالية", "Invoices, reconciliation, financial records"),
    integ("pay", "مدفوعات", "Payments", "Payment gateway", "معاملات مربوطة بالتذكرة", "Ticket-bound transactions"),
    integ("msg", "رسائل", "Messaging", "WhatsApp / SMS", "إشعارات تشغيلية للحالة والتسليم", "Operational status and handover notices"),
    integ("vision", "ذكاء", "AI", "Vision / extraction", "استخراج منظم من صور الاستقبال", "Structured extraction from intake photos"),
  ],
  stack: [
    { layer: "interface", items: ["TanStack Start", "PWA", "RTL UI"], responsibility: L("واجهات العميل والفرق", "Guest and field interfaces") },
    { layer: "application", items: ["Supabase", "RLS", "Signed URLs"], responsibility: L("قواعد العمل والصلاحيات", "Business rules and access") },
    { layer: "data", items: ["PostgreSQL", "Private storage"], responsibility: L("حالة المركبة والأصول", "Vehicle state and assets") },
    { layer: "intelligence", items: ["Vehicle photo extraction"], responsibility: L("تسريع الاستقبال", "Intake acceleration") },
    { layer: "deployment", items: ["Cloudflare Workers"], responsibility: L("نشر وتشغيل الحافة", "Edge deploy and runtime") },
  ],
  mass,
  capabilities: ["product", "ux", "frontend", "backend", "data", "ai", "integrations", "operations"],
  outcomes: [
    { from: L("ورق واتصال هاتفي", "Paper and phone calls"), to: L("تذكرة رقمية وحالة مشتركة", "Digital ticket and shared state") },
    { from: L("بحث يدوي عن المركبة", "Manual vehicle search"), to: L("موقع معيّن وتوجيه قابل للتتبع", "Assigned location and traceable dispatch") },
    { from: L("دفع غير متتبع", "Untracked payment"), to: L("معاملة مربوطة بالمحاسبة", "Transaction bound to accounting") },
    { from: L("رؤية موقع واحد مكسورة", "Broken single-site visibility"), to: L("تشغيل متعدد المواقع متسق", "Consistent multi-site operations") },
  ],
  arkanScope: [
    L("استراتيجية المنتج", "Product strategy"),
    L("معمارية النظام", "System architecture"),
    L("تجربة الاستخدام", "UX"),
    L("الواجهة", "Frontend"),
    L("الأنظمة الخلفية", "Backend"),
    L("البيانات", "Database"),
    L("التكاملات", "Integrations"),
    L("الذكاء الاصطناعي", "AI"),
    L("النشر", "Deployment"),
    L("التشغيل", "Operations"),
  ],
  relatedProjects: ["rentara", "nexora-erp"],
  scale: scaleFromMass(mass, 4),
  dna: ["ops", "saas", "ai", "pwa"],
  atlas: { x: 72, y: 32 },
};
