import type { Project } from "../types";
import {
  L,
  behind,
  integ,
  mod,
  role,
  scaleFromMass,
  techWhy,
  wf,
} from "../projectBuilders";

const mass = {
  modules: 5,
  roles: 5,
  workflows: 4,
  interfaces: 3,
  integrations: 4,
  automations: 1,
  dataDomains: 6,
} as const;

export const nexoraErp: Project = {
  id: "NXR-01",
  slug: "nexora-erp",
  title: L("Nexora ERP", "Nexora ERP"),
  descriptor: L(
    "منصة أنظمة أعمال متعددة الوحدات بحوكمة أدوار وتفعيل مرحلي.",
    "Multi-module business systems platform with role governance and phased activation.",
  ),
  summary: L(
    "منصة مؤسسية تربط التشغيل والمالية والموارد البشرية والتقارير تحت صلاحيات دقيقة ووحدات قابلة للتفعيل.",
    "Enterprise platform connecting operations, finance, HR, and reporting under precise permissions and activatable modules.",
  ),
  context: L(
    "منظمات تنمو بأدوات متفرقة — جداول، أنظمة جزئية، وصلاحيات غير متسقة — فتحتاج حوكمة تشغيلية واحدة دون استبدال كل شيء دفعة واحدة.",
    "Growing organizations run on scattered tools—spreadsheets, partial systems, inconsistent permissions—and need one operating governance without a big-bang rip-and-replace.",
  ),
  challenge: L(
    "بلا مصدر حقيقة مشترك للأدوار والبيانات، تتكاثر النسخ ويتعذّر التدقيق، وقرار الإدارة يعتمد على تقارير متأخرة وغير متوافقة.",
    "Without a shared source of truth for roles and data, copies multiply, audit breaks, and management decides from late, mismatched reports.",
  ),
  thinking: L(
    "المشكلة ليست «إضافة ERP». المشكلة تصميم حدود الوحدات والصلاحيات ومسار التفعيل بحيث يبقى النظام قابلًا للنمو دون فوضى.",
    "The problem is not “adding an ERP.” It is designing module boundaries, permissions, and activation so the system can grow without chaos.",
  ),
  solution: L(
    "بنية منصّة: هوية وصلاحيات في المركز، وحدات تشغيل/مالية/موارد بشرية قابلة للتفعيل، ومسارات موافقة وتقارير فوق بيانات مشتركة.",
    "Platform architecture: identity and permissions at the core, activatable ops/finance/HR modules, with approvals and reporting over shared data.",
  ),
  impact: L(
    "أساس قابل للتوسع لحوكمة وتشغيل موحّد عبر الأقسام — تفعيل بالوحدة بدل مشروع إعادة بناء كامل.",
    "A scalable foundation for unified governance across departments—module activation instead of a full rebuild project.",
  ),
  behindInterface: behind(
    "تفعيل وحدة",
    "Activate a module",
    [
      ["طلب", "Request"],
      ["مراجعة صلاحيات", "Permission review"],
      ["موافقة", "Approval"],
      ["تهيئة بيانات", "Data bootstrap"],
      ["تفعيل", "Activation"],
      ["تدقيق", "Audit"],
    ],
    "ما تراه مفتاح تشغيل. ما يحدث إعادة تشكيل حدود النظام والصلاحيات.",
    "What you see is a toggle. What happens is a reshape of system boundaries and permissions.",
  ),
  techRationale: [
    techWhy(
      "الوحدات يجب أن تُحمَّل كحدود منتج واضحة لا كصفحات مترابطة عشوائيًا.",
      "Modules must load as clear product boundaries—not loosely linked pages.",
      "واجهة وحدات وTypeScript يفرضان عقودًا بين الطبقات.",
      "Feature modules and TypeScript enforce contracts across layers.",
      ["React", "TypeScript", "Feature modules"],
    ),
    techWhy(
      "كل إجراء حساس يحتاج تحقق صلاحية على الخادم مع أثر تدقيق.",
      "Every sensitive action needs server-side permission checks with an audit trail.",
      "طبقات نطاق وRBAC ومسارات API تفصل القواعد عن الواجهة.",
      "Domain layers, RBAC, and API routes keep rules out of the UI.",
      ["Domain layers", "API routes", "RBAC"],
    ),
    techWhy(
      "البيانات المؤسسية تحتاج هجرات منضبطة وتاريخ تغيير قابل للمراجعة.",
      "Enterprise data needs disciplined migrations and reviewable change history.",
      undefined,
      undefined,
      ["PostgreSQL", "Migrations", "Audit trails"],
    ),
    techWhy(
      "المنصة تتطور طويلًا — القرارات المعمارية يجب أن تُوثَّق وتُختبر.",
      "The platform evolves over years—architecture decisions must be documented and tested.",
      undefined,
      undefined,
      ["ADRs", "Sprint history", "Testing harness"],
    ),
  ],
  sector: "services",
  systemType: "erp",
  status: "evolving",
  featured: true,
  region: ["Egypt"],
  roles: [
    role(
      "admin",
      "مسؤول",
      "Admin",
      "ضبط الهوية والوحدات والصلاحيات دون كسر التشغيل الجاري.",
      "Configure identity, modules, and permissions without breaking live ops.",
      "المنصة: مستخدمون، أدوار، وحدات مفعّلة، وسجل تدقيق.",
      "Platform: users, roles, active modules, and audit log.",
      "يمنح الوصول، يفعّل الوحدات، ويراجع التغييرات الحساسة.",
      "Grants access, activates modules, and reviews sensitive changes.",
      ["platform"],
      ["governance"],
    ),
    role(
      "finance",
      "مالية",
      "Finance",
      "مسارات مالية متسقة مع القيود والصلاحيات — لا جداول موازية.",
      "Financial flows consistent with constraints and permissions—no parallel sheets.",
      "قيود، تسويات، وحالات موافقة مالية.",
      "Entries, reconciliations, and finance approval states.",
      "يسجّل ويراجع ويغلق الدورات المالية ضمن الصلاحية.",
      "Posts, reviews, and closes finance cycles within permission.",
      ["finance"],
      ["reporting", "ops-flow"],
    ),
    role(
      "ops",
      "تشغيل",
      "Operations",
      "تنفيذ يومي عبر الأقسام فوق بيانات مشتركة لا نسخ محلية.",
      "Day-to-day execution across departments on shared data—not local copies.",
      "طوابير عمل، حالات، واستثناءات تشغيلية.",
      "Work queues, states, and operational exceptions.",
      "يدخل وينفّذ ويصعّد ضمن مسار الموافقة.",
      "Enters, executes, and escalates within the approval path.",
      ["ops"],
      ["ops-flow"],
    ),
    role(
      "hr",
      "موارد بشرية",
      "HR",
      "سجلات أفراد وأدوار مرتبطة بالصلاحيات التشغيلية.",
      "People records and roles bound to operational permissions.",
      "ملفات، تعيينات، وحالات مرتبطة بالهوية.",
      "Profiles, assignments, and states linked to identity.",
      "يدير السجلات ويحدّث الارتباط بالأدوار.",
      "Maintains records and keeps role linkage current.",
      ["hr"],
      ["ops-flow"],
    ),
    role(
      "manager",
      "إدارة",
      "Management",
      "قرارات من مؤشرات موحّدة لا تقارير متعارضة.",
      "Decisions from unified indicators—not conflicting reports.",
      "لوحات مؤشرات ومسارات موافقة إدارية.",
      "KPI boards and management approval paths.",
      "يعتمد، يوجّه، ويراجع الأداء عبر الوحدات.",
      "Approves, steers, and reviews performance across modules.",
      ["reports"],
      ["reporting", "governance"],
    ),
  ],
  modules: [
    mod(
      "platform",
      "المنصة والصلاحيات",
      "Platform & roles",
      "هوية وصلاحيات ووحدات قابلة للتفعيل وسجل تدقيق.",
      "Identity, permissions, activatable modules, and audit log.",
      "يمنع وصولًا أوسع من الحاجة ويفصل تفعيل القدرة عن الواجهة فقط.",
      "Stops over-broad access and separates capability activation from UI-only toggles.",
      "RBAC، طلبات وصول، وتفعيل وحدات ببوابات موافقة.",
      "RBAC, access requests, and module activation behind approval gates.",
      "أساس لكل الوحدات والتقارير.",
      "Foundation for every module and report.",
    ),
    mod(
      "ops",
      "الوحدات التشغيلية",
      "Operational modules",
      "عمليات يومية عبر الأقسام فوق كيانات مشتركة.",
      "Day-to-day operations across departments on shared entities.",
      "يزيل الازدواج بين الفرق في إدخال الحالة نفسها.",
      "Removes duplicate entry of the same state across teams.",
      "مسارات إدخال → مراجعة → تنفيذ مع حالات واضحة.",
      "Entry → review → execute paths with explicit states.",
      "يغذي المالية والتقارير والاستثناءات.",
      "Feeds finance, reporting, and exceptions.",
    ),
    mod(
      "finance",
      "المالية",
      "Finance",
      "مسارات مالية وتسويات مرتبطة بالأحداث التشغيلية.",
      "Financial flows and reconciliations tied to operational events.",
      "يربط الأثر المالي بالعملية لا بنسخة جدول لاحقة.",
      "Binds financial effect to the operation—not a later spreadsheet copy.",
      "قيود، موافقات، وتسويات قابلة للتدقيق.",
      "Entries, approvals, and auditable reconciliations.",
      "يرتبط بالتشغيل والتقارير وواجهات التكامل.",
      "Links to ops, reporting, and integration APIs.",
    ),
    mod(
      "hr",
      "الموارد البشرية",
      "HR",
      "أدوار وبيانات أفراد مرتبطة بالهوية والصلاحيات.",
      "People roles and records bound to identity and permissions.",
      "يمنع فصل ملف الموظف عن ما يستطيع فعله في النظام.",
      "Stops decoupling the employee record from what they can do in the system.",
      "سجلات، تعيينات، ومزامنة أدوار.",
      "Records, assignments, and role sync.",
      "يغذي المنصة والتشغيل.",
      "Feeds platform and operations.",
    ),
    mod(
      "reports",
      "لوحات المؤشرات",
      "KPI dashboards",
      "رؤية تنفيذية موحّدة من نفس مصدر البيانات.",
      "Unified executive visibility from the same data source.",
      "يلغي تعارض «تقرير القسم» مع «تقرير الإدارة».",
      "Ends conflicting department reports versus management reports.",
      "تجميع مضبوط بالصلاحيات ولوحات حسب الدور.",
      "Permission-scoped aggregation and role-based boards.",
      "يقرأ من التشغيل والمالية دون كتابة مسار بديل.",
      "Reads from ops and finance without a parallel write path.",
    ),
  ],
  workflows: [
    wf(
      "governance",
      "الحوكمة",
      "Governance",
      [
        ["طلب صلاحية/وحدة", "Access / module request"],
        ["مراجعة", "Review"],
        ["موافقة", "Approval"],
        ["تفعيل", "Activation"],
      ],
      "management",
    ),
    wf(
      "ops-flow",
      "التشغيل",
      "Operations",
      [
        ["إدخال", "Entry"],
        ["مراجعة", "Review"],
        ["تنفيذ", "Execute"],
        ["إغلاق", "Close"],
      ],
      "operations",
    ),
    wf(
      "reporting",
      "التقارير",
      "Reporting",
      [
        ["تجميع", "Aggregate"],
        ["لوحة", "Dashboard"],
        ["قرار", "Decision"],
      ],
      "management",
    ),
    wf(
      "exceptions",
      "الاستثناءات",
      "Exceptions",
      [
        ["تعارض", "Conflict"],
        ["تصعيد", "Escalate"],
        ["حل", "Resolve"],
      ],
      "exceptions",
    ),
  ],
  integrations: [
    integ("api", "واجهات", "APIs", "Internal platform APIs", "ربط الوحدات الداخلية بعقود واضحة", "Connect internal modules on clear contracts"),
    integ("report", "تقارير", "Reporting", "Reporting pipelines", "تجميع مؤشرات تشغيلية ومالية", "Aggregate operational and financial indicators"),
    integ("identity", "هوية", "Identity", "Auth / directory", "مزامنة مستخدمين ومجموعات عند الحاجة", "Sync users and groups when required"),
    integ("export", "تصدير", "Export", "Accounting export", "مخرجات مالية للأنظمة الخارجية", "Finance outputs to external systems"),
  ],
  stack: [
    { layer: "frontend", items: ["React", "TypeScript", "Feature modules"], responsibility: L("واجهات الوحدات حسب الدور", "Role-scoped module surfaces") },
    { layer: "backend", items: ["Domain layers", "API routes", "RBAC"], responsibility: L("قواعد العمل والصلاحيات", "Business rules and permissions") },
    { layer: "data", items: ["PostgreSQL", "Migrations", "Audit trails"], responsibility: L("مصدر حقيقة قابل للتدقيق", "Auditable source of truth") },
    { layer: "ops", items: ["ADRs", "Sprint history", "Testing harness"], responsibility: L("تطوّر منضبط للمنصة", "Disciplined platform evolution") },
  ],
  mass,
  capabilities: ["product", "ux", "frontend", "backend", "data", "integrations", "operations"],
  outcomes: [
    { from: L("جداول وأنظمة متفرقة", "Scattered sheets and tools"), to: L("منصة وحدات بحوكمة واحدة", "Modular platform under one governance") },
    { from: L("صلاحيات ضعيفة أو يدوية", "Weak or manual permissions"), to: L("RBAC وتفعيل مرحلي", "RBAC with phased activation") },
    { from: L("تقارير متعارضة", "Conflicting reports"), to: L("مؤشرات من مصدر مشترك", "Indicators from a shared source") },
    { from: L("إعادة بناء كاملة لكل احتياج", "Full rebuild per need"), to: L("تفعيل وحدة عند الجاهزية", "Module activation when ready") },
  ],
  arkanScope: [
    L("استراتيجية المنتج", "Product strategy"),
    L("معمارية النظام", "System architecture"),
    L("الواجهة", "Frontend"),
    L("الأنظمة الخلفية", "Backend"),
    L("البيانات", "Database"),
    L("التكاملات", "Integrations"),
    L("التشغيل", "Operations"),
  ],
  relatedProjects: ["masar-valet", "rentara"],
  scale: scaleFromMass(mass, 5),
  dna: ["rbac", "enterprise", "modules"],
  atlas: { x: 22, y: 28 },
};
