import type { Project } from "../types";
import {
  L,
  behind,
  integ,
  mod,
  role,
  scaleFromMass,
  techWhy,
  wf,
} from "../projectBuilders";

const mass = {
  modules: 7,
  roles: 4,
  workflows: 3,
  interfaces: 3,
  integrations: 4,
  automations: 4,
  dataDomains: 4,
} as const;

export const noxusWhatsappAi: Project = {
  id: "NXS-01",
  slug: "noxus-whatsapp-ai",
  title: L("NOXUS", "NOXUS"),
  descriptor: L("طبقة ذكاء رسائل للتشغيل", "AI messaging layer for operations"),
  summary: L(
    "طبقة واتساب قابلة للدمج تُضيف ذكاءً مؤسسًا على معرفة العمل وواجهات برمجة حية — لا كمنتج وكالة ذكاء اصطناعي، بل كطبقة تجعل أنظمة التشغيل أذكى.",
    "An embeddable WhatsApp layer that adds grounded intelligence from business knowledge and live APIs — not as an AI-agency product, but as the layer that makes operating systems smarter.",
  ),
  context: L(
    "الفرق التشغيلية تتحدث مع العملاء على واتساب بينما الحقيقة تعيش في أنظمة أخرى: قائمة، مخزون، مواعيد، تذاكر. الرسائل بلا سياق تخلق وعودًا خاطئة، والبوابات التي «ترسل رسالة فقط» لا تغلق حلقة التشغيل.",
    "Ops teams talk to customers on WhatsApp while truth lives elsewhere: menu, stock, appointments, tickets. Context-free messages create wrong promises, and gateways that only send messages never close the operating loop.",
  ),
  challenge: L(
    "روبوتات معزولة ووكالات «ذكاء اصطناعي» تبيع محادثة منفصلة عن نظام العمل. النتيجة: هلوسة، معرفة ثابتة تتقادم فور تغيّر السعر أو المخزون، وعدم قدرة المنتج التشغيلي على استدعاء الطبقة من داخله.",
    "Isolated bots and “AI agency” offerings sell conversation detached from the business system. Result: hallucination, stale knowledge the moment price or stock changes, and no way for the operating product to call the layer from inside.",
  ),
  thinking: L(
    "الذكاء الاصطناعي هنا ليس المنتج. المنتج هو نظام التشغيل؛ NOXUS طبقة تجعله أذكى على قناة واتساب. المعرفة المؤسسية وأوامر API الحية (`/slug`) تُحقن في الرد، والـ SDK يجعل الطبقة قابلة للدمج — لا وجهة بديلة يهاجر إليها العمل.",
    "AI is not the product here. The product is the operating system; NOXUS is the layer that makes it smarter on WhatsApp. Company knowledge and live API slash commands (`/slug`) are injected into replies, and the SDK makes the layer embeddable — not a destination the business migrates to.",
  ),
  solution: L(
    "منصة واتساب مفتوحة: محرك جلسات ورسائل، وكيل مؤسس على معرفة العمل واستجابات API حية، لوحة تشغيل ثنائية اللغة، وSDK/REST لدمج الطبقة داخل أنظمة الأعمال — مع حواجز ضد الهلوسة وسجل تفاعل قابل للتدقيق.",
    "An open WhatsApp platform: session and messaging engine, a grounded agent on business knowledge and live API responses, a bilingual ops dashboard, and SDK/REST to embed the layer inside business systems — with anti-hallucination guards and an auditable interaction log.",
  ),
  impact: L(
    "من قناة رسائل معزولة إلى طبقة ذكاء قابلة للدمج فوق أنظمة التشغيل الحالية.",
    "From an isolated messaging channel to an embeddable intelligence layer on top of existing operating systems.",
  ),
  behindInterface: behind(
    "عميل يسأل على واتساب عن توفر أو سعر",
    "Customer asks on WhatsApp about availability or price",
    [
      [
        "استقبال الرسالة عبر محرك الجلسات",
        "Message is received through the session engine",
      ],
      [
        "قراءة Reply Data واستخراج أوامر /slug",
        "Reply Data is read and /slug commands are extracted",
      ],
      [
        "جلب واجهات العمل الحية بالتوازي ضمن مهلة وحجم محدودين",
        "Live business APIs are fetched in parallel within timeout and size caps",
      ],
      [
        "توليد رد مؤسس على المعرفة + JSON الحي فقط",
        "A reply is generated only from knowledge + live JSON",
      ],
      [
        "إن لم يوجد غطاء: تصعيد للفريق بدل الاختراع",
        "If uncovered: escalate to the team instead of inventing",
      ],
      [
        "تسجيل القرار (رد / تخطي / فشل) للتدقيق",
        "Decision (replied / skipped / failed) is logged for audit",
      ],
    ],
    "الرد الذكي ليس عرضًا — هو استعلام تشغيلي على قناة العميل.",
    "The smart reply is not a demo — it is an operational query on the customer channel.",
  ),
  techRationale: [
    techWhy(
      "الذكاء مؤسس على معرفة العمل والـ API — لا على ذاكرة عامة.",
      "Intelligence is grounded in business knowledge and APIs — not general memory.",
      "السعر والمخزون يتغيران؛ أوامر `/slug` تجلب الحقيقة الحية قبل الرد، وإن نقص السياق يُصعَّد للبشر.",
      "Price and stock change; `/slug` commands fetch live truth before reply, and missing context escalates to humans.",
      ["Grounded Gemini", "API slash commands", "No-hallucination guard"],
    ),
    techWhy(
      "طبقة قابلة للدمج أهم من منتج محادثة مغلق.",
      "An embeddable layer matters more than a closed chat product.",
      "REST وSDK يسمحان لأنظمة مثل مسار أو نقاط البيع باستدعاء واتساب والذكاء دون إعادة بناء القناة.",
      "REST and SDK let systems like valet or POS call WhatsApp and intelligence without rebuilding the channel.",
      ["WhatsApp REST API", "Product SDK", "Webhooks"],
    ),
    techWhy(
      "لوحة تشغيل وسجل تفاعل جزء من الحوكمة.",
      "Ops dashboard and interaction log are part of governance.",
      "الفرق تحتاج اختبار API، تبريد لكل محادثة، وإيقاف ردود المجموعات افتراضيًا — لا «سحرًا» بلا أثر.",
      "Teams need API tests, per-chat cooldown, and group replies off by default — not magic without a trail.",
      ["React dashboard", "Audit log", "Docker-native deploy"],
    ),
  ],
  sector: "ventures",
  systemType: "ai",
  status: "venture",
  featured: true,
  region: ["Egypt"],
  roles: [
    role(
      "ops",
      "تشغيل المحادثات",
      "Conversation ops",
      "تشغيل القناة بمعرفة حية دون هلوسة.",
      "Run the channel with live knowledge and without hallucination.",
      "جلسات، Reply Data، نتائج اختبار API، وسجل التفاعل.",
      "Sessions, Reply Data, API test results, and interaction log.",
      "ضبط المعرفة، تفعيل الأوامر، ومراجعة التصعيد.",
      "Tune knowledge, enable commands, and review escalations.",
      ["knowledge", "flows", "dashboard", "sessions"],
      ["grounded-reply", "escalation"],
    ),
    role(
      "dev",
      "مطوّر أنظمة",
      "Systems developer",
      "دمج الطبقة داخل منتج العمل عبر SDK/REST.",
      "Embed the layer inside the business product via SDK/REST.",
      "مفاتيح، Webhooks، أوامر API، وتوثيق الدمج.",
      "Keys, webhooks, API commands, and embed docs.",
      "تسجيل واجهات `/slug` واستدعاء الإرسال من النظام الأم.",
      "Register `/slug` APIs and call send from the parent system.",
      ["sdk", "flows", "sessions"],
      ["embed"],
    ),
    role(
      "admin",
      "مسؤول المنصة",
      "Platform admin",
      "حوكمة البنية والتبريد والأمان التشغيلي.",
      "Govern infrastructure, cooldowns, and operational safety.",
      "إعدادات المحرك، التخزين، والمستخدمون.",
      "Engine settings, storage, and users.",
      "ضبط الحدود، المجموعات، وسياسات الرد.",
      "Configure limits, groups, and reply policies.",
      ["dashboard", "sessions", "knowledge"],
      ["grounded-reply", "escalation"],
    ),
    role(
      "customer",
      "عميل على واتساب",
      "WhatsApp customer",
      "إجابة دقيقة من حقيقة العمل أو تحويل واضح للفريق.",
      "An accurate answer from business truth — or a clear handoff to the team.",
      "محادثة واتساب بلغته.",
      "A WhatsApp thread in their language.",
      "السؤال والحصول على رد مؤسس أو متابعة بشرية.",
      "Ask and receive a grounded reply or human follow-up.",
      ["flows", "sessions"],
      ["grounded-reply", "escalation"],
    ),
  ],
  modules: [
    mod(
      "sessions",
      "محرك الجلسات",
      "Session engine",
      "واتساب: جلسات، رسائل، وسائط، مجموعات، وتسميات.",
      "WhatsApp: sessions, messages, media, groups, and labels.",
      "بوابة إرسال بلا حالة تشغيل قابلة للإدارة.",
      "A send gateway with no manageable ops state.",
      "محرك رسائل كامل مع REST للتحكم البرمجي.",
      "Full messaging engine with REST for programmatic control.",
      "يحمل طبقة الذكاء ولوحة التشغيل والـ SDK.",
      "Carries the intelligence layer, ops dashboard, and SDK.",
    ),
    mod(
      "knowledge",
      "معرفة العمل",
      "Business knowledge",
      "Reply Data مؤسسي مع إشارات `/slug` للبيانات الحية.",
      "Institutional Reply Data with `/slug` pointers to live data.",
      "معرفة ثابتة تتقادم وتدفع للهلوسة.",
      "Static knowledge that goes stale and invites hallucination.",
      "ملف معرفة + جلب API متوازٍ قبل التوليد.",
      "Knowledge file + parallel API fetch before generation.",
      "يؤسس كل رد ذكي ويمنع الاختراع خارج الغطاء.",
      "Grounds every smart reply and blocks invention outside coverage.",
    ),
    mod(
      "flows",
      "تدفقات الرد",
      "Reply flows",
      "تبريد لكل محادثة، أمان المجموعات، وتصعيد عند نقص السياق.",
      "Per-chat cooldown, group safety, and escalate-when-uncovered.",
      "عواصف ردود أو إجابات خارج نطاق العمل.",
      "Reply storms or answers outside business scope.",
      "سياسات قابلة للضبط في المحرك وسجل القرار.",
      "Configurable engine policies and decision logging.",
      "يربط الرسالة بالذكاء ثم بالفريق عند الحاجة.",
      "Connects message to intelligence, then to humans when needed.",
    ),
    mod(
      "dashboard",
      "لوحة التشغيل",
      "Operations dashboard",
      "واجهة عربية/إنجليزية للجلسات والذكاء والـ webhooks والتدقيق.",
      "AR/EN UI for sessions, AI, webhooks, and audit.",
      "تشغيل صندوق أسود بلا اختبار أو أثر.",
      "Black-box ops with no tests or trail.",
      "اختبار API لحظة بلحظة وعرض حالة آخر استدعاء.",
      "One-click API tests and last-call status visibility.",
      "سطح الحوكمة فوق المحرك والمعرفة.",
      "Governance surface over engine and knowledge.",
    ),
    mod(
      "sdk",
      "SDK الدمج",
      "Embed SDK",
      "أدوات لزرع الطبقة داخل أنظمة الأعمال.",
      "Tooling to plant the layer inside business systems.",
      "واتساب كمنتج منفصل عن نظام التشغيل.",
      "WhatsApp as a product separate from the operating system.",
      "SDK وتوثيق استدعاء من المنتج الأم.",
      "SDK and docs for calls from the parent product.",
      "يجعل NOXUS طبقة لا وجهة.",
      "Makes NOXUS a layer, not a destination.",
    ),
    mod(
      "webhooks",
      "Webhooks",
      "Webhooks",
      "أحداث خارجة لإغلاق الحلقة مع أنظمة أخرى.",
      "Outbound events to close the loop with other systems.",
      "ذكاء يبقى داخل صندوق الرسائل.",
      "Intelligence that stays trapped inside the inbox.",
      "اشتراك أحداث لتشغيل لاحق في ERP/OPS.",
      "Event subscriptions for downstream ERP/OPS actions.",
      "يربط الرد الذكي بمسارات العمل الخلفية.",
      "Binds smart replies to backend work paths.",
    ),
    mod(
      "audit",
      "سجل التفاعل",
      "Interaction audit",
      "سؤال، قرار، سبب — محفوظة للتدقيق.",
      "Question, decision, reason — persisted for audit.",
      "لا أثر يفسر لماذا رد النظام أو صمت.",
      "No trail explaining why the system replied or stayed silent.",
      "تخزين تفاعلي لكل قرار رد/تخطي/فشل.",
      "Interaction store for every replied/skipped/failed decision.",
      "يغذي تحسين المعرفة وثقة التشغيل.",
      "Feeds knowledge tuning and operational trust.",
    ),
  ],
  workflows: [
    wf(
      "grounded-reply",
      "رد مؤسس",
      "Grounded reply",
      [
        ["استقبال", "Receive"],
        ["استخراج /slug", "Extract /slug"],
        ["جلب حي", "Live fetch"],
        ["رد مؤسس", "Grounded reply"],
      ],
      "operations",
    ),
    wf(
      "embed",
      "الدمج في النظام",
      "Embed into system",
      [
        ["تسجيل أوامر API", "Register API commands"],
        ["ضبط Reply Data", "Configure Reply Data"],
        ["استدعاء SDK/REST", "Call SDK/REST"],
        ["تشغيل من المنتج الأم", "Operate from parent product"],
      ],
      "operations",
    ),
    wf(
      "escalation",
      "التصعيد",
      "Escalation",
      [
        ["سؤال خارج الغطاء", "Uncovered question"],
        ["رفض الاختراع", "Refuse to invent"],
        ["تحويل للفريق", "Hand to team"],
        ["تسجيل السبب", "Log reason"],
      ],
      "exceptions",
    ),
  ],
  integrations: [
    integ(
      "whatsapp",
      "رسائل",
      "Messaging",
      "WhatsApp engine",
      "قناة العميل والجلسات والوسائط",
      "Customer channel, sessions, and media",
    ),
    integ(
      "llm",
      "ذكاء",
      "Intelligence",
      "Grounded Gemini",
      "توليد ردود مقيدة بمعرفة العمل والسياق الحي",
      "Generate replies constrained by business knowledge and live context",
    ),
    integ(
      "business-apis",
      "أنظمة عمل",
      "Business systems",
      "Slash-command APIs",
      "قائمة، مخزون، مواعيد — حقيقة حية وقت الرد",
      "Menu, stock, appointments — live truth at reply time",
    ),
    integ(
      "sdk",
      "دمج",
      "Embed",
      "Product SDK / REST",
      "زرع الطبقة داخل أنظمة التشغيل الحالية",
      "Plant the layer inside existing operating systems",
    ),
  ],
  stack: [
    {
      layer: "interface",
      items: ["React dashboard", "Bilingual RTL/LTR ops UI"],
      responsibility: L(
        "تشغيل شفاف للمعرفة والجلسات والتدقيق.",
        "Transparent ops for knowledge, sessions, and audit.",
      ),
    },
    {
      layer: "application",
      items: ["NestJS", "WhatsApp REST", "Webhook pipeline", "SDK"],
      responsibility: L(
        "محرك رسائل ودمج قابل للاستدعاء من أنظمة أخرى.",
        "Messaging engine and embed surface callable by other systems.",
      ),
    },
    {
      layer: "intelligence",
      items: [
        "Grounded Gemini",
        "Reply Data",
        "API slash commands",
        "Anti-hallucination policy",
      ],
      responsibility: L(
        "ذكاء يجعل التشغيل أذكى — لا يستبدله.",
        "Intelligence that makes ops smarter — not a replacement for them.",
      ),
    },
    {
      layer: "data",
      items: ["Pluggable DB (SQLite/Postgres)", "Interaction logs", "Cache/storage adapters"],
    },
    {
      layer: "deployment",
      items: ["Docker Compose", "Self-host or noxusai.online"],
    },
  ],
  mass: { ...mass },
  capabilities: [
    "ai",
    "product",
    "frontend",
    "backend",
    "integrations",
    "operations",
  ],
  outcomes: [
    {
      from: L("روبوت محادثة معزول", "Isolated chatbot"),
      to: L("طبقة ذكاء فوق نظام التشغيل", "Intelligence layer on the operating system"),
    },
    {
      from: L("معرفة ثابتة تتقادم", "Stale static knowledge"),
      to: L("سياق حي عبر أوامر API", "Live context via API commands"),
    },
    {
      from: L("هلوسة أو وعود خاطئة", "Hallucination or wrong promises"),
      to: L("رد مؤسس أو تصعيد للفريق", "Grounded reply or team escalation"),
    },
    {
      from: L("واتساب كمنتج منفصل", "WhatsApp as a separate product"),
      to: L("SDK قابل للزرع في أنظمة العمل", "SDK plantable into business systems"),
    },
  ],
  arkanScope: [
    L("تعريف الطبقة لا منتج الوكالة", "Layer definition — not an agency product"),
    L("معمارية محرك واتساب ودمج", "WhatsApp engine and embed architecture"),
    L("ذكاء مؤسس وأوامر API حية", "Grounded intelligence and live API commands"),
    L("لوحة تشغيل وتدقيق", "Ops dashboard and audit"),
    L("SDK وتوثيق الدمج", "SDK and embed documentation"),
    L("نشر ذاتي أو مستضاف", "Self-host or hosted delivery"),
  ],
  relatedProjects: ["masar-valet", "velora-pos", "hakimo-production"],
  scale: scaleFromMass(mass, 3),
  dna: ["ai", "whatsapp", "sdk", "grounded", "ops-layer"],
  liveUrl: "https://noxusai.online/",
  atlas: { x: 84, y: 22 },
};
