import type { Project } from "../types";
import {
  L,
  mod,
  role,
  wf,
  integ,
  behind,
  techWhy,
  scaleFromMass,
} from "../projectBuilders";

const mass = {
  modules: 7,
  roles: 5,
  workflows: 3,
  interfaces: 3,
  integrations: 3,
  automations: 1,
  dataDomains: 6,
  locations: 3,
} as const;

export const qrMenu: Project = {
  id: "QRM-01",
  slug: "qr-menu",
  title: L("QR Menu", "QR Menu"),
  descriptor: L("تجربة قائمة رقمية", "Digital menu experience"),
  summary: L(
    "منصة قوائم رقمية للمطاعم والمقاهي: مسح QR، قائمة عامة ثنائية اللغة، إدارة فروع ومنتجات، وتوليد أكواد — دون تطبيق على جهاز الضيف.",
    "Digital menu platform for restaurants and cafés: QR scan, bilingual public menu, branch and product CMS, and code generation — no guest app install.",
  ),
  context: L(
    "المطاعم تحتاج تحديث أسعار وأصناف وصور فورًا عبر الفروع، بينما يفتح الضيف القائمة من هاتفه خلال ثوانٍ — بالعربية والإنجليزية، وبهوية المطعم لا بهوية المنصة.",
    "Restaurants need instant price, item, and photo updates across branches, while guests open the menu from their phone in seconds — Arabic and English, branded as the venue, not the platform.",
  ),
  challenge: L(
    "القوائم الورقية مكلفة وبطيئة التحديث؛ الروابط العشوائية بلا صلاحيات؛ والتجارب العامة غالبًا تُظهر علامة تقنية بدل علامة المطعم.",
    "Paper menus are costly and slow to update; ad-hoc links lack permissions; public experiences often show a tech brand instead of the restaurant.",
  ),
  thinking: L(
    "القائمة العامة سطح تجربة؛ خلفها مستأجرون وفروع وصلاحيات وثيمات. فصلنا تجربة الضيف عن لوحة الإدارة، وجعلنا العلامة المعروضة للمطعم — مع مسارات منصة لمن يدير عدة علامات.",
    "The public menu is an experience surface; behind it are tenants, branches, permissions, and themes. We separated guest experience from the admin console, and made the visible brand the restaurant — with platform paths for multi-brand operators.",
  ),
  solution: L(
    "PWA قائمة عامة مع ثيمات وRTL، ولوحة إدارة للفروع والأصناف والإضافات والأحجام وQR، وصلاحيات (مالك/مدير/كاشير/عارض) فوق PostgreSQL عبر Prisma — مع جاهزية طلبات وطاولات ومدفوعات حسب الخطة.",
    "Public menu PWA with themes and RTL, plus an admin console for branches, items, add-ons, sizes, and QR — roles (owner/manager/cashier/viewer) on PostgreSQL via Prisma, with ordering/tables/payments readiness by plan.",
  ),
  impact: L(
    "من قائمة ورقية ثابتة إلى تجربة ضيف قابلة للتحديث فورًا، مع حوكمة محتوى لكل فرع.",
    "From a static paper menu to an instantly updatable guest experience, with per-branch content governance.",
  ),
  behindInterface: behind(
    "الضيف يمسح QR على الطاولة",
    "Guest scans the table QR",
    [
      [
        "فتح رابط القائمة العامة للفرع/السمة الصحيحة",
        "Open the public menu URL for the correct branch/theme",
      ],
      [
        "تحميل التصنيفات والمنتجات والأحجام مع دعم RTL واللغة",
        "Load categories, products, and sizes with RTL and locale",
      ],
      [
        "عرض هوية المطعم (شعار/غلاف/ساعات) لا علامة المنصة",
        "Render restaurant identity (logo/cover/hours), not platform brand",
      ],
      [
        "بحث وتصفية وتفاصيل صنف؛ نية طلب عند تفعيل المسار",
        "Search, filter, item detail; order intent when path is enabled",
      ],
    ],
    "المسح يفتح تجربة المطعم — المحتوى يُدار من لوحة الصلاحيات خلفها.",
    "The scan opens the restaurant’s experience — content is governed from the permissioned console behind it.",
  ),
  techRationale: [
    techWhy(
      "بدون تطبيق: قائمة تعمل كصفحة/PWA فورية",
      "No install: menu as an instant page/PWA",
      "ضيف الطاولة لن يحمّل تطبيقًا؛ Next.js وPWA يُبقيان المسار خفيفًا وقابلًا للمشاركة.",
      "Table guests will not install an app; Next.js and PWA keep the path light and shareable.",
      ["Next.js 16", "PWA", "Framer Motion"],
    ),
    techWhy(
      "عربية أولًا مع إنجليزية متكافئة",
      "Arabic-first with equal English",
      "next-intl وRTL يجعلان التبديل اللغوي جزءًا من التجربة لا طبقة لاحقة.",
      "next-intl and RTL make locale switching part of the experience, not an afterthought.",
      ["next-intl", "RTL"],
    ),
    techWhy(
      "CMS بصلاحيات فوق بيانات علائقية واضحة",
      "Permissioned CMS on clear relational data",
      "Prisma وPostgreSQL ينظّمان المطاعم والفروع والمنتجات؛ JWT والأدوار تحمي لوحة الإدارة.",
      "Prisma and PostgreSQL structure restaurants, branches, and products; JWT and roles protect the admin console.",
      ["PostgreSQL", "Prisma", "JWT auth"],
    ),
    techWhy(
      "QR كأصل تشغيلي قابل للتنزيل",
      "QR as a downloadable operational asset",
      "توليد PNG/SVG لكل فرع يربط الطاولة بالمحتوى الصحيح دون إعادة طباعة القائمة كاملة.",
      "PNG/SVG generation per branch binds the table to the right content without reprinting the whole menu.",
      ["QRCode"],
    ),
  ],
  sector: "commerce",
  systemType: "experience",
  status: "deployed",
  featured: true,
  roles: [
    role(
      "guest",
      "ضيف",
      "Guest",
      "قائمة سريعة وواضحة بلا تسجيل.",
      "A fast, clear menu with no sign-in.",
      "تصنيفات، أصناف، شارات، تفاصيل، وبحث.",
      "Categories, items, badges, detail, and search.",
      "تصفح، حفظ مفضلات محليًا، ومشاركة الرابط.",
      "Browse, save local favorites, and share the link.",
      ["public-menu"],
      ["browse"],
    ),
    role(
      "owner",
      "مالك",
      "Owner",
      "سيطرة كاملة على الفروع والمحتوى والمستخدمين والخطة.",
      "Full control of branches, content, users, and plan.",
      "لوحة الإدارة، الفروع، المنتجات، QR، والإعدادات.",
      "Admin console, branches, products, QR, and settings.",
      "إدارة مستخدمين، ثيمات، وحدود الاشتراك.",
      "Manage users, themes, and subscription limits.",
      ["admin", "branches", "catalog", "qr", "themes"],
      ["publish", "qr-deploy"],
    ),
    role(
      "manager",
      "مدير",
      "Manager",
      "تحديث يومي للقائمة عبر الفروع المسموح بها.",
      "Day-to-day menu updates across allowed branches.",
      "تصنيفات، منتجات، إضافات، وأحجام.",
      "Categories, products, add-ons, and sizes.",
      "نشر تغييرات المحتوى وتوليد QR للفرع.",
      "Publish content changes and generate branch QR.",
      ["admin", "catalog", "qr"],
      ["publish", "qr-deploy"],
    ),
    role(
      "cashier",
      "كاشير",
      "Cashier",
      "اطّلاع تشغيلي مرتبط بالخدمة عند تفعيل الطلبات.",
      "Operational visibility tied to service when ordering is on.",
      "حالات طلب/طاولة ضمن صلاحية محدودة.",
      "Order/table states within limited permission.",
      "متابعة الطلبات دون تعديل الكتالوج الكامل.",
      "Follow orders without full catalog edits.",
      ["admin"],
      ["browse"],
    ),
    role(
      "viewer",
      "عارض",
      "Viewer",
      "مراجعة المحتوى بلا تعديل.",
      "Review content without editing.",
      "عرض القائمة ولوحات ملخصة للقراءة فقط.",
      "Menu view and summary boards — read only.",
      "تصفح الحالة المنشورة فقط.",
      "Browse published state only.",
      ["admin", "public-menu"],
      ["browse"],
    ),
  ],
  modules: [
    mod(
      "public-menu",
      "القائمة العامة",
      "Public menu",
      "تجربة الضيف: تصنيفات، أصناف، بحث، وRTL.",
      "Guest experience: categories, items, search, and RTL.",
      "قائمة ورقية أو رابط ثابت بلا تجربة.",
      "Paper menu or a static link with no experience.",
      "صفحة/PWA عامة مربوطة بفرع وثيم ولغة.",
      "Public page/PWA bound to branch, theme, and locale.",
      "يربط الكتالوج والثيمات وQR.",
      "Connects catalog, themes, and QR.",
    ),
    mod(
      "catalog",
      "الكتالوج",
      "Catalog",
      "منتجات، تصنيفات، صور، شارات، أحجام، وإضافات.",
      "Products, categories, images, badges, sizes, and add-ons.",
      "محتوى غير متسق بين الفروع.",
      "Inconsistent content across branches.",
      "نماذج محتوى مع ربط اختياري لكل فرع.",
      "Content models with optional per-branch binding.",
      "يربط القائمة العامة ولوحة الإدارة.",
      "Connects public menu and admin console.",
    ),
    mod(
      "branches",
      "الفروع",
      "Branches",
      "فروع متعددة تحت مطعم واحد.",
      "Multiple branches under one restaurant.",
      "قائمة واحدة لكل المواقع رغم اختلاف التوفر.",
      "One menu for all sites despite different availability.",
      "فرع له قائمة وQR وإعدادات مستقلة ضمن المستأجر.",
      "Branch with its own menu, QR, and settings within the tenant.",
      "يربط الكتالوج وQR والصلاحيات.",
      "Connects catalog, QR, and permissions.",
    ),
    mod(
      "qr",
      "مولد QR",
      "QR generator",
      "أصول QR قابلة للتنزيل (PNG/SVG).",
      "Downloadable QR assets (PNG/SVG).",
      "أكواد عشوائية تنكسر عند تغيير الرابط.",
      "Ad-hoc codes that break when the URL changes.",
      "توليد مربوط بمسار القائمة العامة للفرع.",
      "Generation bound to the branch public menu path.",
      "يربط الفروع والتجربة العامة.",
      "Connects branches and the public experience.",
    ),
    mod(
      "admin",
      "لوحة الإدارة",
      "Admin console",
      "إدارة المحتوى والمستخدمين والإعدادات.",
      "Content, users, and settings management.",
      "تعديل عبر المطوّر أو ملفات مشتركة.",
      "Edits via a developer or shared files.",
      "لوحة بصلاحيات أدوار ولوحة عامة للمستأجر.",
      "Role-permissioned console and tenant overview.",
      "يربط كل وحدات المحتوى بالمستخدمين.",
      "Connects all content modules to users.",
    ),
    mod(
      "themes",
      "الثيمات",
      "Themes",
      "مظاهر قائمة قابلة للاختيار/الشراء حسب الخطة.",
      "Menu looks selectable/purchasable by plan.",
      "شكل واحد لا يناسب علامات مختلفة.",
      "One look that fails different brands.",
      "ثيمات تُطبَّق على التجربة العامة دون تغيير البيانات.",
      "Themes applied to the public experience without changing data.",
      "يربط القائمة العامة والاشتراك.",
      "Connects public menu and subscription.",
    ),
    mod(
      "ordering",
      "الطلبات والطاولات",
      "Ordering & tables",
      "مسارات طلب وطاولات ومدفوعات حسب الخطة.",
      "Order, table, and payment paths by plan.",
      "قائمة للعرض فقط بينما التشغيل يحتاج نية طلب.",
      "View-only menu while ops need order intent.",
      "نماذج طلب/طاولة/دفع جاهزة للتفعيل التدريجي.",
      "Order/table/payment models ready for progressive enablement.",
      "يربط القائمة العامة والتشغيل عند التفعيل.",
      "Connects public menu and ops when enabled.",
    ),
  ],
  workflows: [
    wf(
      "browse",
      "تصفح الضيف",
      "Guest browse",
      [
        ["مسح QR", "Scan QR"],
        ["تصفح التصنيفات", "Browse categories"],
        ["تفاصيل صنف", "Item detail"],
        ["نية طلب / مشاركة", "Order intent / share"],
      ],
      "customer",
    ),
    wf(
      "publish",
      "نشر المحتوى",
      "Publish content",
      [
        ["تعديل صنف", "Edit item"],
        ["ضبط فرع", "Scope branch"],
        ["حفظ", "Save"],
        ["ظهور فوري للقائمة", "Live on public menu"],
      ],
      "operations",
    ),
    wf(
      "qr-deploy",
      "نشر QR",
      "QR deploy",
      [
        ["اختيار فرع", "Select branch"],
        ["توليد رمز", "Generate code"],
        ["تنزيل PNG/SVG", "Download PNG/SVG"],
        ["طباعة للطاولات", "Print for tables"],
      ],
      "operations",
    ),
  ],
  integrations: [
    integ(
      "qrcode",
      "QR",
      "QR",
      "QRCode library",
      "توليد أصول الفروع للطباعة",
      "Generate branch assets for print",
    ),
    integ(
      "payments",
      "مدفوعات",
      "Payments",
      "Paymob / cash paths",
      "مسارات دفع عند تفعيل الطلبات",
      "Payment paths when ordering is enabled",
    ),
    integ(
      "auth",
      "هوية",
      "Identity",
      "JWT role auth",
      "حماية لوحة الإدارة بالأدوار",
      "Protect admin console with roles",
    ),
  ],
  stack: [
    {
      layer: "interface",
      items: ["Next.js 16", "Tailwind 4", "shadcn/ui", "Framer Motion", "PWA"],
      responsibility: L(
        "تجربة ضيف ولوحة إدارة",
        "Guest experience and admin console",
      ),
    },
    {
      layer: "application",
      items: ["next-intl", "JWT auth", "RBAC"],
      responsibility: L(
        "لغة وصلاحيات ومسارات مستأجر",
        "Locale, permissions, and tenant routes",
      ),
    },
    {
      layer: "data",
      items: ["PostgreSQL", "Prisma"],
      responsibility: L(
        "مطاعم وفروع ومنتجات وQR",
        "Restaurants, branches, products, and QR",
      ),
    },
    {
      layer: "business",
      items: ["Plans", "Themes", "Menu catalog", "Ordering models"],
      responsibility: L(
        "حدود الاشتراك وتجربة القائمة",
        "Subscription limits and menu experience",
      ),
    },
    {
      layer: "deployment",
      items: ["Vercel", "Docker Compose (local DB)"],
      responsibility: L(
        "نشر الواجهة وقاعدة محلية للتطوير",
        "App deploy and local DB for development",
      ),
    },
  ],
  mass: { ...mass },
  capabilities: ["ux", "frontend", "backend", "product", "operations"],
  outcomes: [
    {
      from: L("قائمة ورقية", "Paper menu"),
      to: L("تجربة رقمية فورية", "Instant digital experience"),
    },
    {
      from: L("تحديث بطيء", "Slow updates"),
      to: L("نشر محتوى من اللوحة", "Console-published content"),
    },
    {
      from: L("رابط عشوائي", "Ad-hoc link"),
      to: L("QR مربوط بالفرع", "Branch-bound QR"),
    },
    {
      from: L("علامة تقنية ظاهرة", "Visible tech brand"),
      to: L("هوية المطعم للضيف", "Restaurant identity for guests"),
    },
  ],
  arkanScope: [
    L("تجربة الاستخدام", "UX"),
    L("استراتيجية المنتج", "Product strategy"),
    L("الواجهة", "Frontend"),
    L("الأنظمة الخلفية", "Backend"),
    L("البيانات", "Database"),
    L("التشغيل", "Operations"),
  ],
  relatedProjects: ["velora-pos"],
  scale: scaleFromMass(mass, 3),
  dna: ["commerce", "rtl", "pwa", "qr", "multi-tenant"],
  atlas: { x: 30, y: 62 },
};
