import type { Project } from "../types";
import {
  L,
  mod,
  role,
  wf,
  integ,
  behind,
  techWhy,
  scaleFromMass,
} from "../projectBuilders";

const mass = {
  modules: 9,
  roles: 4,
  workflows: 4,
  interfaces: 2,
  integrations: 3,
  automations: 2,
  dataDomains: 7,
  locations: 3,
} as const;

export const rentara: Project = {
  id: "RNT-01",
  slug: "rentara",
  title: L("Rentara", "Rentara"),
  descriptor: L("تشغيل وحدات إيجارية", "Rental units operations"),
  summary: L(
    "لوحة داخلية ثنائية اللغة لإدارة المواقع والوحدات والمستأجرين والعقود والفواتير والمدفوعات، مع صلاحيات دقيقة وتكامل Odoo اختياري.",
    "Bilingual internal console for locations, units, tenants, contracts, invoices, and payments — with precise permissions and optional Odoo sync.",
  ),
  context: L(
    "تشغيل إيجاري في السوق السعودي يحتاج سجل وحدات وعقود ومستحقات يمكن للفريق الداخلي الاعتماد عليه يوميًا بالعربية والإنجليزية، مع فصل واضح بين من يعدّل ومن يطّلع فقط.",
    "Saudi rental operations need a units, contracts, and dues register the internal team can trust daily in Arabic and English — with a clear split between who edits and who only views.",
  ),
  challenge: L(
    "وحدات وعقود ومدفوعات موزّعة على جداول ومحادثات؛ استحقاقات الشهر وأعمار الديون تُحسب يدويًا؛ والربط المحاسبي إما غائب أو غير متزامن.",
    "Units, contracts, and payments scattered across sheets and chats; monthly dues and debt aging computed by hand; accounting link missing or out of sync.",
  ),
  thinking: L(
    "هذا ليس موقع تسويق عقاري؛ هو نظام تشغيل داخلي. الأولوية لسجلات موثوقة، صلاحيات على مستوى الخادم وRLS، وتدفقات استحقاق/تحصيل يمكن مطابقتها — ثم تكامل محاسبي اختياري دون جعل Odoo شرطًا لكل خطوة.",
    "This is not a real-estate marketing site; it is an internal operating system. Priority: trustworthy records, server-side permissions plus RLS, and dues/collection flows that can be reconciled — then optional accounting sync without making Odoo a gate for every step.",
  ),
  solution: L(
    "Dashboard داخلي (Next.js + next-intl RTL) فوق Supabase: مواقع ووحدات ومستأجرون وعقود وفواتير ومدفوعات وتقارير استحقاق/أعمار ديون، مع أدوار وصلاحيات وتدقيق، ومسار Odoo XML-RPC حيث يحتاجه التشغيل.",
    "Internal dashboard (Next.js + next-intl RTL) on Supabase: locations, units, tenants, contracts, invoices, payments, due/aging reports — with roles, permissions, audit, and an Odoo XML-RPC path where operations need it.",
  ),
  impact: L(
    "من متابعة يدوية متفرقة إلى تشغيل إيجاري قابل للمراجعة: وحدة → عقد → فاتورة → تحصيل → تقرير.",
    "From scattered manual follow-up to reviewable rental operations: unit → contract → invoice → collection → report.",
  ),
  behindInterface: behind(
    "المحرر يسجّل دفعة على فاتورة مستحقة",
    "Editor posts a payment on a due invoice",
    [
      [
        "التحقق من الجلسة وصلاحية التعديل (لا عرض فقط)",
        "Validate session and edit permission (not view-only)",
      ],
      [
        "ربط الدفعة بالفاتورة والمستأجر والوحدة",
        "Bind payment to invoice, tenant, and unit",
      ],
      [
        "تحديث حالة التحصيل (جزئي / مكتمل) وأعمار الدين",
        "Update collection state (partial / paid) and aging",
      ],
      [
        "كتابة سجل تدقيق؛ وإخراج إلى Odoo عند تفعيل المزامنة",
        "Write audit log; outbox to Odoo when sync is enabled",
      ],
    ],
    "الدفعة ليست رقمًا في خلية — هي حدث تشغيلي يحرّك الحالة والتقارير.",
    "A payment is not a cell value — it is an operational event that moves state and reports.",
  ),
  techRationale: [
    techWhy(
      "عربية/إنجليزية كمواطنَين متساويين في لوحة داخلية",
      "Arabic and English as equal citizens in an internal console",
      "فريق التشغيل يعمل باللغتين؛ next-intl مع RTL يحافظ على المسارات والمعنى دون واجهتين.",
      "Ops teams work in both languages; next-intl with RTL keeps routes and meaning without two UIs.",
      ["next-intl", "RTL"],
    ),
    techWhy(
      "الصلاحيات على الواجهة والخادم وRLS معًا",
      "Permissions on UI, server, and RLS together",
      "العارض لا يرى أزرار التعديل، والخادم يرفض الكتابة، وRLS يمنع الصفوف — دفاع متعدد الطبقات.",
      "Viewers lose edit controls, the server rejects writes, and RLS blocks rows — defense in depth.",
      ["Supabase Auth", "RLS", "RBAC"],
    ),
    techWhy(
      "Odoo اختياري عبر مسار مزامنة صريح",
      "Optional Odoo through an explicit sync path",
      "التشغيل اليومي يبقى داخل Rentara؛ المحاسبة تُزامَن عبر سجلات ومخرجات يمكن تتبعها عند الحاجة.",
      "Day-to-day ops stay inside Rentara; accounting syncs through traceable logs and outbox when needed.",
      ["Odoo XML-RPC", "Sync logs", "Outbox"],
    ),
    techWhy(
      "مراقبة أخطاء التشغيل في الإنتاج",
      "Production ops error observability",
      "Sentry يلتقط فشل المسارات الحساسة دون تعريض بيانات حساسة في الواجهة.",
      "Sentry catches sensitive-path failures without exposing sensitive data in the UI.",
      ["Sentry"],
    ),
  ],
  sector: "operations",
  systemType: "operations",
  status: "deployed",
  featured: true,
  region: ["Saudi Arabia"],
  roles: [
    role(
      "admin-editor",
      "مدير / محرر",
      "Admin / Editor",
      "إدارة كاملة للوحدات والعقود والتحصيل والمستخدمين.",
      "Full control of units, contracts, collection, and users.",
      "كل الوحدات التشغيلية، الفواتير، المدفوعات، والاستيراد.",
      "All operating modules, invoices, payments, and import.",
      "إنشاء وتعديل وترحيل دفعات وإدارة الصلاحيات.",
      "Create, edit, post payments, and manage permissions.",
      [
        "locations",
        "units",
        "tenants",
        "contracts",
        "billing",
        "permissions",
        "import",
      ],
      ["lease", "collect", "import-flow"],
    ),
    role(
      "ops",
      "تشغيل",
      "Operations",
      "متابعة الاستحقاقات والتحصيل اليومي بدقة الوحدات.",
      "Track dues and daily collection at unit precision.",
      "لوحة الاستحقاق، انتظار الدفع، والجزئي والكامل.",
      "Due board, awaiting payment, partial and fully paid.",
      "تحديث حالات التحصيل وربطها بالفواتير.",
      "Update collection states and bind them to invoices.",
      ["units", "billing", "reporting"],
      ["collect", "aging"],
    ),
    role(
      "finance",
      "مالية",
      "Finance",
      "مطابقة الفواتير والمدفوعات والربط المحاسبي.",
      "Reconcile invoices, payments, and accounting link.",
      "الفواتير، المدفوعات، أعمار الديون، وسجلات Odoo.",
      "Invoices, payments, debt aging, and Odoo logs.",
      "مراجعة التحصيل وتفعيل/متابعة المزامنة المحاسبية.",
      "Review collection and drive accounting sync.",
      ["billing", "reporting", "odoo"],
      ["collect", "aging"],
    ),
    role(
      "viewer",
      "مشاهد",
      "Viewer",
      "اطّلاع تشغيلي بلا تعديل — للرقابة والمتابعة.",
      "Operational read-only access — for oversight and follow-up.",
      "لوحات وتقارير وقوائم وحدات/فواتير للعرض فقط.",
      "Dashboards, reports, and unit/invoice lists — view only.",
      "تصفح الحالات دون إنشاء أو تعديل أو دفع.",
      "Browse states without create, edit, or payment actions.",
      ["reporting", "units", "billing"],
      ["aging"],
    ),
  ],
  modules: [
    mod(
      "locations",
      "المواقع",
      "Locations",
      "تجميع الوحدات تحت مواقع تشغيلية.",
      "Group units under operating locations.",
      "وحدات بلا سياق مكاني واضح للفريق.",
      "Units without clear place context for the team.",
      "سجل مواقع يربط الوحدات والتقارير.",
      "Location registry binding units and reports.",
      "يربط الوحدات والتقارير والاستيراد.",
      "Connects units, reports, and import.",
    ),
    mod(
      "units",
      "الوحدات",
      "Units",
      "سجل الوحدات وحالاتها التشغيلية.",
      "Unit registry and operating states.",
      "قوائم وحدات متضاربة بين الجداول.",
      "Conflicting unit lists across spreadsheets.",
      "وحدة واحدة كمصدر حقيقة للحالة والعقد.",
      "One unit as source of truth for state and contract.",
      "يربط المواقع والمستأجرين والعقود.",
      "Connects locations, tenants, and contracts.",
    ),
    mod(
      "tenants",
      "المستأجرون",
      "Tenants",
      "بيانات المستأجرين وارتباطهم بالوحدات.",
      "Tenant records linked to units.",
      "مستأجرون مكررون أو ناقصو البيانات عند التحصيل.",
      "Duplicate or incomplete tenants at collection time.",
      "ملف مستأجر مربوط بالعقود والفواتير.",
      "Tenant profile bound to contracts and invoices.",
      "يربط العقود والتحصيل.",
      "Connects contracts and collection.",
    ),
    mod(
      "contracts",
      "العقود",
      "Contracts",
      "عقود وبنود ومرفقات تشغيلية.",
      "Contracts, lines, and operational attachments.",
      "اتفاقات شفهية أو ملفات بلا حالة نظامية.",
      "Verbal deals or files without system state.",
      "عقد بحالات وبنود يفعّل مسار الفوترة.",
      "Contract with states and lines that enable billing.",
      "يربط الوحدات والمستأجرين والفواتير.",
      "Connects units, tenants, and invoices.",
    ),
    mod(
      "billing",
      "الفواتير والمدفوعات",
      "Invoices & payments",
      "استحقاق، تحصيل جزئي/كامل، وسجل دفع.",
      "Dues, partial/full collection, and payment history.",
      "تحصيل بلا أثر على حالة الفاتورة.",
      "Collection with no effect on invoice state.",
      "دفعات تُحدّث حالة الفاتورة وتغذية التقارير.",
      "Payments update invoice state and feed reports.",
      "يربط العقود والتقارير وOdoo.",
      "Connects contracts, reports, and Odoo.",
    ),
    mod(
      "reporting",
      "التقارير",
      "Reporting",
      "مستحق هذا الشهر، انتظار الدفع، وأعمار الديون.",
      "Due this month, awaiting payment, and debt aging.",
      "تقارير تُبنى يدويًا في نهاية الشهر.",
      "Reports built manually at month end.",
      "لوحات من نفس سجلات الفواتير والمدفوعات.",
      "Boards from the same invoice and payment records.",
      "يربط التحصيل والإدارة المالية.",
      "Connects collection and finance leadership.",
    ),
    mod(
      "permissions",
      "الصلاحيات",
      "Permissions",
      "أدوار وصلاحيات دقيقة على العمليات.",
      "Roles and fine-grained operation permissions.",
      "وصول فضفاض لبيانات إيجارية حساسة.",
      "Loose access to sensitive rental data.",
      "أدوار نظامية ومخصّصة مع رفض على الخادم وRLS.",
      "System and custom roles with server and RLS denial.",
      "يربط كل الوحدات بالهوية.",
      "Connects every module to identity.",
    ),
    mod(
      "import",
      "الاستيراد",
      "Import",
      "استيراد تشغيلي مع سجلات تنفيذ.",
      "Operational import with run logs.",
      "إدخال جماعي يفسد السجلات بلا أثر.",
      "Bulk entry that corrupts records with no trail.",
      "مسارات استيراد مع سجل ما نجح وما فشل.",
      "Import paths with success/failure logs.",
      "يربط الوحدات والمستأجرين والتدقيق.",
      "Connects units, tenants, and audit.",
    ),
    mod(
      "odoo",
      "مزامنة Odoo",
      "Odoo sync",
      "ربط محاسبي اختياري عبر XML-RPC وسجلات مزامنة.",
      "Optional accounting link via XML-RPC and sync logs.",
      "محاسبة منفصلة تعيد إدخال نفس الأرقام.",
      "Separate accounting that re-keys the same numbers.",
      "مخرجات ومزامنة قابلة للتتبع دون حجب التشغيل المحلي.",
      "Traceable outbox and sync without blocking local ops.",
      "يربط الفواتير والمدفوعات بالمحاسبة.",
      "Connects invoices and payments to accounting.",
    ),
  ],
  workflows: [
    wf(
      "lease",
      "التأجير",
      "Lease",
      [
        ["اختيار وحدة", "Select unit"],
        ["ربط مستأجر", "Attach tenant"],
        ["إنشاء عقد", "Create contract"],
        ["تفعيل", "Activate"],
      ],
      "operations",
    ),
    wf(
      "collect",
      "التحصيل",
      "Collection",
      [
        ["استحقاق", "Due"],
        ["فاتورة", "Invoice"],
        ["دفعة", "Payment"],
        ["تسوية حالة", "Settle state"],
      ],
      "finance",
    ),
    wf(
      "aging",
      "أعمار الديون",
      "Debt aging",
      [
        ["تجميع مستحقات", "Aggregate dues"],
        ["تصنيف عمر", "Age buckets"],
        ["متابعة", "Follow up"],
        ["تقرير", "Report"],
      ],
      "management",
    ),
    wf(
      "import-flow",
      "الاستيراد",
      "Import",
      [
        ["رفع ملف", "Upload file"],
        ["تحقق", "Validate"],
        ["تنفيذ", "Execute"],
        ["سجل النتائج", "Log results"],
      ],
      "operations",
    ),
  ],
  integrations: [
    integ(
      "odoo",
      "محاسبة",
      "Accounting",
      "Odoo XML-RPC",
      "مزامنة فواتير/مدفوعات اختيارية مع سجلات تتبع",
      "Optional invoice/payment sync with trace logs",
    ),
    integ(
      "sentry",
      "مراقبة",
      "Observability",
      "Sentry",
      "تتبع أخطاء مسارات التشغيل الحساسة",
      "Track errors on sensitive ops paths",
    ),
    integ(
      "auth",
      "هوية",
      "Identity",
      "Supabase Auth",
      "جلسات وأدوار مع RLS",
      "Sessions and roles with RLS",
    ),
  ],
  stack: [
    {
      layer: "interface",
      items: ["Next.js 16", "React", "Tailwind", "next-intl", "RTL"],
      responsibility: L(
        "لوحة داخلية ثنائية اللغة",
        "Bilingual internal console",
      ),
    },
    {
      layer: "application",
      items: ["Server Actions", "Services", "Repositories"],
      responsibility: L(
        "طبقة تشغيل واضحة: UI → Actions → Services → DB",
        "Clear ops layer: UI → Actions → Services → DB",
      ),
    },
    {
      layer: "data",
      items: ["Supabase", "PostgreSQL", "RLS", "Storage"],
      responsibility: L(
        "سجلات إيجارية محمية بالصلاحيات",
        "Rental records protected by permissions",
      ),
    },
    {
      layer: "business",
      items: ["Contracts", "Invoices", "Payments", "RBAC"],
      responsibility: L(
        "قواعد التأجير والتحصيل",
        "Lease and collection rules",
      ),
    },
    {
      layer: "ops",
      items: ["Sentry", "Audit logs", "Odoo sync logs"],
      responsibility: L(
        "مراقبة ومراجعة ومزامنة",
        "Observability, review, and sync",
      ),
    },
  ],
  mass: { ...mass },
  capabilities: [
    "frontend",
    "backend",
    "data",
    "integrations",
    "operations",
  ],
  outcomes: [
    {
      from: L("جداول ومحادثات", "Sheets and chats"),
      to: L("لوحة تشغيل داخلية", "Internal ops console"),
    },
    {
      from: L("استحقاق يدوي", "Manual dues"),
      to: L("تحصيل بحالة نظامية", "Collection with system state"),
    },
    {
      from: L("صلاحيات غير واضحة", "Unclear access"),
      to: L("تعديل مقابل عرض فقط", "Edit vs view-only"),
    },
    {
      from: L("محاسبة منفصلة", "Separate accounting"),
      to: L("مزامنة اختيارية قابلة للتتبع", "Optional traceable sync"),
    },
  ],
  arkanScope: [
    L("معمارية النظام", "System architecture"),
    L("الواجهة", "Frontend"),
    L("الأنظمة الخلفية", "Backend"),
    L("البيانات والصلاحيات", "Data & permissions"),
    L("التكاملات", "Integrations"),
    L("التشغيل", "Operations"),
  ],
  relatedProjects: ["masar-valet", "nexora-erp"],
  scale: scaleFromMass(mass, 4),
  dna: ["rtl", "supabase", "ops", "rbac", "odoo"],
  atlas: { x: 58, y: 55 },
};
