import type { Project } from "../types";
import {
  L,
  behind,
  integ,
  mod,
  role,
  scaleFromMass,
  techWhy,
  wf,
} from "../projectBuilders";

const mass = {
  modules: 7,
  roles: 5,
  workflows: 3,
  interfaces: 3,
  integrations: 4,
  automations: 2,
  dataDomains: 4,
} as const;

export const sokanyCommerce: Project = {
  id: "SKN-01",
  slug: "sokany-commerce",
  title: L("Sokany Commerce", "Sokany Commerce"),
  descriptor: L("قناة تجارة وعلامة", "Brand commerce channel"),
  summary: L(
    "مكدس تجارة لعلامة أجهزة منزلية: متجر عربي أولًا، كتالوج غني لتحسين الظهور، وطبقة تشغيل تربط الواجهة بـ WooCommerce دون كشف أسرار الخادم للمتصفح.",
    "A commerce stack for a home-appliance brand: Arabic-first storefront, SEO-ready catalog, and an ops layer that binds the UI to WooCommerce without exposing server secrets to the browser.",
  ),
  context: L(
    "علامة أجهزة منزلية تحتاج قناة رقمية تليق بالعلامة: تصفح سريع، صفحات منتج قوية للبحث، سلة ودفع محلي، وإدارة كتالوج تبقى في WordPress/WooCommerce بينما تتغير تجربة المتجر باستقلالية.",
    "A home-appliance brand needs a digital channel that fits the brand: fast browse, search-strong product pages, local checkout, and catalog ops that stay in WordPress/WooCommerce while the storefront can evolve independently.",
  ),
  challenge: L(
    "فصل بين محتوى العلامة والمخزون والطلبات وتجربة الشراء. القوالب التقليدية تبطئ الواجهة وتضعف SEO، ومفاتيح التجارة لا يجب أن تصل للمتصفح، والدفع المحلي يحتاج مسارًا واضحًا للتحقق من الاستدعاء الراجع.",
    "Brand content, stock, orders, and the buying experience are disconnected. Classic themes slow the UI and weaken SEO, commerce keys must never reach the browser, and local payments need a clear callback verification path.",
  ),
  thinking: L(
    "المتجر ليس صفحة تسويق — هو قناة تشغيل: اكتشاف → ثقة → طلب → تنفيذ. لذلك نفصل واجهة العلامة عن محرك التجارة، نبقي الأسرار في مسارات خادم (BFF)، ونصمّم العربية/RTL كأساس لا كترجمة لاحقة.",
    "The store is not a marketing page — it is an operating channel: discovery → trust → order → fulfilment. So we separate the brand UI from the commerce engine, keep secrets in server routes (BFF), and treat Arabic/RTL as the foundation — not a later translation.",
  ),
  solution: L(
    "واجهة Next.js عربية أولًا فوق WooCommerce عبر طبقة API خادمية، مع كتالوج وصلاحيات محتوى، SEO وJSON-LD، سلة وحالة مستمرة، ومسارات دفع (مثل فوري) والدفع عند الاستلام جاهزة للتحقق والتوسع.",
    "An Arabic-first Next.js storefront over WooCommerce via a server API layer, with catalog and content controls, SEO and JSON-LD, persistent cart state, and payment paths (e.g. Fawry) plus cash-on-delivery ready for verification and growth.",
  ),
  impact: L(
    "من قناة ضعيفة أو قالب جاهز إلى واجهة علامة قابلة للنمو مربوطة بتشغيل كتالوج وطلبات حقيقي.",
    "From a weak channel or stock theme to a growth-ready brand surface tied to real catalog and order operations.",
  ),
  behindInterface: behind(
    "العميل يضيف منتجًا إلى السلة ويكمل الطلب",
    "Customer adds a product to cart and completes checkout",
    [
      [
        "طلب بيانات المنتج عبر مسارات الخادم فقط",
        "Product data is fetched through server routes only",
      ],
      [
        "التحقق من الشكل والأسعار عبر مخططات صارمة",
        "Shape and price checks run through strict schemas",
      ],
      [
        "تحديث سلة مستمرة دون كسر الترطيب بين الخادم والعميل",
        "Persisted cart updates without SSR/client hydration breaks",
      ],
      [
        "إنشاء طلب في WooCommerce من الطبقة الخادمية",
        "Order is created in WooCommerce from the server layer",
      ],
      [
        "مسار دفع موقّع أو تأكيد الدفع عند الاستلام",
        "Signed payment path or cash-on-delivery confirmation",
      ],
    ],
    "الواجهة تبيع؛ الخادم يحمي التجارة ويملك الحقيقة.",
    "The interface sells; the server protects commerce and owns the truth.",
  ),
  techRationale: [
    techWhy(
      "Headless يفصل سرعة العلامة عن استقرار محرك الطلبات.",
      "Headless separates brand speed from order-engine stability.",
      "الفريق التسويقي يبقى على WooCommerce؛ تجربة المتجر تُنشر وتتطور على Next دون إعادة بناء الإدارة.",
      "Marketing stays on WooCommerce; the storefront ships and evolves on Next without rebuilding admin.",
      ["Next.js", "WooCommerce REST", "BFF API routes"],
    ),
    techWhy(
      "أسرار التجارة لا تغادر الخادم.",
      "Commerce secrets never leave the server.",
      "مفاتيح المستهلك تُستدعى فقط من Route Handlers؛ المتصفح يتحدث مع تطبيقك لا مع WooCommerce مباشرة.",
      "Consumer keys are used only from route handlers; the browser talks to your app, not WooCommerce directly.",
      ["Server-only env", "Zod boundary parsing"],
    ),
    techWhy(
      "عربي أولًا وتحسين ظهور المنتج جزء من البنية لا من الإضافات.",
      "Arabic-first and product discoverability are structural, not add-ons.",
      "RTL، البيانات الوصفية، JSON-LD، وخريطة الموقع تُبنى مع صفحات المنتج لا بعدها.",
      "RTL, metadata, JSON-LD, and sitemap ship with product pages — not after them.",
      ["next-intl / RTL layout", "JSON-LD", "Sitemap"],
    ),
  ],
  sector: "commerce",
  systemType: "commerce",
  status: "deployed",
  featured: true,
  region: ["Egypt"],
  roles: [
    role(
      "customer",
      "عميل",
      "Customer",
      "تصفح وثقة وشراء بلا احتكاك، بالعربية أولًا.",
      "Browse, trust, and buy with low friction — Arabic first.",
      "كتالوج، عروض، صفحات منتج، سلة، ودفع.",
      "Catalog, offers, product pages, cart, and checkout.",
      "الشراء، تتبع حالة الطلب الظاهرة، ومشاركة المنتج.",
      "Purchase, see order state, and share products.",
      ["storefront", "catalog", "cart", "checkout"],
      ["purchase"],
    ),
    role(
      "content",
      "محتوى العلامة",
      "Brand content",
      "صفحات تشرح الضمان والعروض دون كسر مسار الشراء.",
      "Warranty and offer pages that do not break the buy path.",
      "محتوى تسويقي وSEO وصورة العلامة.",
      "Marketing content, SEO, and brand surface.",
      "تحديث الصفحات الثابتة ورسائل الثقة.",
      "Update static pages and trust messaging.",
      ["storefront", "seo"],
      ["purchase"],
    ),
    role(
      "catalog-ops",
      "تشغيل الكتالوج",
      "Catalog ops",
      "إبقاء المنتجات والأسعار والمخزون صحيحة في المصدر.",
      "Keep products, prices, and stock correct at the source.",
      "WooCommerce كمصدر حقيقة للكتالوج والطلبات.",
      "WooCommerce as source of truth for catalog and orders.",
      "إدارة المنتجات والتصنيفات والمخزون من الإدارة.",
      "Manage products, categories, and stock from admin.",
      ["catalog", "orders"],
      ["fulfil", "fulfilment"],
    ),
    role(
      "ops",
      "تشغيل الطلبات",
      "Order ops",
      "تنفيذ الطلبات والدفع المحلي والمتابعة.",
      "Fulfil orders, local payments, and follow-up.",
      "طلبات، حالات دفع، واستثناءات التنفيذ.",
      "Orders, payment states, and fulfilment exceptions.",
      "معالجة الطلب ومسارات الدفع عند الاستلام/فوري.",
      "Process orders and COD / Fawry paths.",
      ["orders", "checkout"],
      ["fulfilment"],
    ),
    role(
      "admin",
      "مسؤول القناة",
      "Channel admin",
      "ضبط البيئة، المفاتيح الخادمية، ووضع التجربة/الحي.",
      "Configure environment, server keys, and mock/live mode.",
      "إعدادات النشر والتكاملات والمراقبة.",
      "Deploy settings, integrations, and monitoring.",
      "تشغيل القناة بأمان وربطها بالمصدر التجاري.",
      "Run the channel safely and keep it bound to commerce source.",
      ["storefront", "catalog", "orders", "seo"],
      ["purchase", "fulfilment"],
    ),
  ],
  modules: [
    mod(
      "storefront",
      "واجهة المتجر",
      "Storefront",
      "تجربة علامة عربية أولًا: رئيسية، متجر، منتج، عروض.",
      "Arabic-first brand experience: home, shop, product, offers.",
      "واجهة لا تعكس قوة العلامة أو سرعة التصفح.",
      "A UI that fails brand strength or browse speed.",
      "صفحات App Router مع RTL وحالة سلة آمنة للترطيب.",
      "App Router pages with RTL and hydration-safe cart state.",
      "يستهلك الكتالوج عبر الطبقة الخادمية فقط.",
      "Consumes catalog only through the server layer.",
    ),
    mod(
      "catalog",
      "الكتالوج",
      "Catalog",
      "منتجات وتصنيفات ومخزون من WooCommerce.",
      "Products, categories, and stock from WooCommerce.",
      "كتالوج متأخر أو غير متسق مع ما يراه العميل.",
      "A catalog that drifts from what the customer sees.",
      "جلب خادمي مع مخططات تحقق ووضع تجريبي/حي.",
      "Server fetch with schema validation and mock/live mode.",
      "يغذي المتجر وSEO ومسارات الطلب.",
      "Feeds storefront, SEO, and order paths.",
    ),
    mod(
      "cart",
      "السلة",
      "Cart",
      "سلة مستمرة وتجربة إضافة متفائلة حيث يلزم.",
      "Persisted cart and optimistic add where appropriate.",
      "فقدان السلة أو تعارض بين الخادم والعميل.",
      "Lost carts or server/client state clashes.",
      "حالة عميل محكومة مع حواجز ترطيب.",
      "Controlled client state with hydration guards.",
      "تمهد للدفع وتنشئ جسرًا للطلب.",
      "Prepares checkout and bridges into the order.",
    ),
    mod(
      "checkout",
      "إتمام الشراء",
      "Checkout",
      "مسارات دفع محلي وطلب خادمي.",
      "Local payment paths and server-side order creation.",
      "دفع غير موثوق أو مفاتيح مكشوفة.",
      "Untrusted payments or exposed keys.",
      "إنشاء طلب + فوري موقّع / الدفع عند الاستلام.",
      "Order create + signed Fawry / cash on delivery.",
      "يربط العميل بتشغيل الطلبات في WooCommerce.",
      "Connects the customer to order ops in WooCommerce.",
    ),
    mod(
      "seo",
      "اكتشاف المنتج",
      "Product discovery",
      "بيانات وصفية، JSON-LD، خريطة موقع، وصف غني.",
      "Metadata, JSON-LD, sitemap, rich product copy.",
      "منتجات موجودة لكن لا تُكتشف.",
      "Products exist but are not discoverable.",
      "طبقات SEO مبنية مع صفحات المنتج.",
      "SEO layers built with product pages.",
      "يزيد جودة القناة دون تغيير محرك الطلبات.",
      "Raises channel quality without changing the order engine.",
    ),
    mod(
      "orders",
      "الطلبات",
      "Orders",
      "دورة الطلب من الإنشاء إلى التنفيذ عبر المصدر التجاري.",
      "Order lifecycle from create to fulfilment via commerce source.",
      "طلبات تُدار خارج النظام أو عبر قنوات متفرقة.",
      "Orders managed outside the system or across scattered channels.",
      "إنشاء وتتبع حالة عبر تكامل WooCommerce الخادمي.",
      "Create and track state via server-side WooCommerce integration.",
      "يغلق حلقة الشراء مع تشغيل المستودع/التوصيل.",
      "Closes the purchase loop with warehouse/delivery ops.",
    ),
    mod(
      "trust",
      "صفحات الثقة",
      "Trust pages",
      "ضمان، إرجاع، تواصل — جزء من مسار الشراء.",
      "Warranty, returns, contact — part of the buy path.",
      "محتوى ثقة معزول عن المتجر.",
      "Trust content isolated from the store.",
      "صفحات ثابتة ثنائية اللغة مربوطة بالتنقل الأساسي.",
      "Bilingual static pages wired into primary navigation.",
      "يرفع إتمام الشراء بدعم قرار العميل.",
      "Lifts conversion by supporting the customer decision.",
    ),
  ],
  workflows: [
    wf(
      "purchase",
      "الشراء",
      "Purchase",
      [
        ["تصفح", "Browse"],
        ["صفحة منتج", "Product page"],
        ["سلة", "Cart"],
        ["دفع", "Checkout"],
        ["تأكيد", "Confirmation"],
      ],
      "customer",
    ),
    wf(
      "catalog-sync",
      "مزامنة الكتالوج",
      "Catalog sync",
      [
        ["تحديث في WooCommerce", "Update in WooCommerce"],
        ["جلب خادمي", "Server fetch"],
        ["تحقق بالمخطط", "Schema validate"],
        ["عرض في المتجر", "Render in storefront"],
      ],
      "operations",
    ),
    wf(
      "fulfilment",
      "التنفيذ",
      "Fulfilment",
      [
        ["استلام طلب", "Receive order"],
        ["تحقق الدفع", "Verify payment"],
        ["تجهيز", "Prepare"],
        ["شحن / تسليم", "Ship / deliver"],
      ],
      "operations",
    ),
  ],
  integrations: [
    integ(
      "woocommerce",
      "تجارة",
      "Commerce",
      "WooCommerce REST API",
      "مصدر حقيقة للمنتجات والطلبات",
      "Source of truth for products and orders",
    ),
    integ(
      "fawry",
      "مدفوعات",
      "Payments",
      "Fawry",
      "إنشاء دفع موقّع واستدعاء راجع للتحقق",
      "Signed payment creation and callback verification",
    ),
    integ(
      "cod",
      "مدفوعات",
      "Payments",
      "Cash on delivery",
      "مسار طلب محلي بدون بوابة فورية",
      "Local order path without an instant gateway",
    ),
    integ(
      "wordpress",
      "محتوى",
      "Content",
      "WordPress admin",
      "إدارة كتالوج ومحتوى دون تغيير الواجهة",
      "Catalog and content admin without changing the UI",
    ),
  ],
  stack: [
    {
      layer: "interface",
      items: ["Next.js", "React", "Tailwind", "Arabic-first RTL"],
      responsibility: L(
        "واجهة علامة سريعة وقابلة للاكتشاف.",
        "Fast, discoverable brand UI.",
      ),
    },
    {
      layer: "application",
      items: ["BFF route handlers", "TanStack Query", "Zustand", "Zod"],
      responsibility: L(
        "حالة العميل وحدود تحقق صارمة.",
        "Client state and strict validation boundaries.",
      ),
    },
    {
      layer: "business",
      items: ["Headless catalog", "Checkout orchestration", "Payment callbacks"],
      responsibility: L(
        "قواعد التجارة خلف الواجهة.",
        "Commerce rules behind the interface.",
      ),
    },
    {
      layer: "data",
      items: ["WooCommerce", "WordPress", "Server-only credentials"],
    },
    {
      layer: "deployment",
      items: ["Vercel", "Env separation", "Mock/live switch"],
    },
  ],
  mass: { ...mass },
  capabilities: [
    "product",
    "ux",
    "frontend",
    "backend",
    "integrations",
    "operations",
  ],
  outcomes: [
    {
      from: L("قالب أو قناة ضعيفة", "Theme or weak channel"),
      to: L("واجهة علامة قابلة للنمو", "Growth-ready brand storefront"),
    },
    {
      from: L("مفاتيح تجارة مكشوفة للعميل", "Commerce keys exposed to the client"),
      to: L("BFF خادمي يحمي الأسرار", "Server BFF that protects secrets"),
    },
    {
      from: L("محتوى ومخزون وطلبات منفصلة", "Split content, stock, and orders"),
      to: L("قناة مربوطة بمصدر تجارة واحد", "Channel bound to one commerce source"),
    },
    {
      from: L("عربي لاحق / SEO ضعيف", "Arabic-later / weak SEO"),
      to: L("عربي أولًا واكتشاف منتج مبني", "Arabic-first with built-in product discovery"),
    },
  ],
  arkanScope: [
    L("استراتيجية قناة العلامة", "Brand channel strategy"),
    L("تجربة شراء عربية أولًا", "Arabic-first purchase UX"),
    L("هندسة headless وBFF", "Headless and BFF architecture"),
    L("تكامل WooCommerce والدفع المحلي", "WooCommerce and local payment integration"),
    L("SEO وبيانات منظمة للمنتج", "SEO and structured product data"),
    L("تشغيل الكتالوج والطلبات", "Catalog and order operations"),
  ],
  relatedProjects: ["souqna", "qr-menu", "velora-pos"],
  scale: scaleFromMass(mass, 4),
  dna: ["commerce", "seo", "brand", "headless", "rtl"],
  liveUrl: "https://sokany-eg.com",
  atlas: { x: 40, y: 78 },
};
