import type { Project } from "../types";
import {
  L,
  behind,
  integ,
  mod,
  role,
  scaleFromMass,
  techWhy,
  wf,
} from "../projectBuilders";

const mass = {
  modules: 5,
  roles: 4,
  workflows: 4,
  interfaces: 4,
  integrations: 3,
  automations: 1,
  dataDomains: 4,
  locations: 1,
} as const;

export const souqna: Project = {
  id: "SQN-01",
  slug: "souqna",
  title: L("سوقنا", "Souqna"),
  descriptor: L(
    "بنية تجارة محلية متعددة الأدوار فوق كتالوج وطلبات وتوصيل مشتركة.",
    "Hyperlocal multi-role commerce infrastructure over shared catalog, orders, and delivery.",
  ),
  summary: L(
    "منصة تجارة محلية عربية أولًا تربط العملاء والتجار ومندوبي التوصيل وإدارة السوق في نظام طلب واحد.",
    "Arabic-first local commerce platform connecting customers, merchants, couriers, and market admin in one order system.",
  ),
  context: L(
    "أسواق محلية تعمل بتواصل يدوي بين متاجر ومندوبين وعملاء — الطلبات تُنسَّق على واتساب والمخزون في الرأس، والتوسع يكسر التنسيق.",
    "Local markets run on manual coordination between shops, couriers, and customers—orders on WhatsApp, stock in someone’s head; growth breaks the coordination.",
  ),
  challenge: L(
    "أدوار متضاربة (عميل/تاجر/مندوب/إدارة) بلا دورة حياة طلب موحّدة — كل طرف يرى جزءًا مختلفًا من الحقيقة.",
    "Conflicting roles (customer/merchant/courier/admin) without one order lifecycle—each party sees a different fragment of truth.",
  ),
  thinking: L(
    "المشكلة ليست متجرًا إلكترونيًا أجمل. المشكلة تشغيل سوق: من يملك الكتالوج، من يقبل الطلب، من يتحرك، ومن يحسم النزاع.",
    "The problem is not a prettier storefront. It is running a market: who owns catalog, who accepts the order, who moves, who resolves disputes.",
  ),
  solution: L(
    "منصة عربية أولًا بتجارب منفصلة لكل دور فوق كتالوج وطلبات وحالات توصيل مشتركة، مع حوكمة سوق للمتاجر والمناطق.",
    "Arabic-first platform with distinct role experiences over shared catalog, orders, and delivery states—plus market governance for merchants and zones.",
  ),
  impact: L(
    "محرك سوق محلي يمكن إطلاق أسواق أو مناطق جديدة عليه دون إعادة بناء دورة الطلب من الصفر.",
    "A local-market engine that can launch new markets or zones without rebuilding the order cycle from scratch.",
  ),
  behindInterface: behind(
    "تأكيد الطلب",
    "Confirm order",
    [
      ["تحقق مخزون", "Stock check"],
      ["قبول تاجر", "Merchant accept"],
      ["تعيين مندوب", "Courier assign"],
      ["استلام", "Pickup"],
      ["تتبع", "Track"],
      ["تسليم", "Deliver"],
      ["إغلاق", "Close"],
    ],
    "ما تراه زر شراء. ما يحدث تنسيق سوق كامل بين أدوار لا ترى شاشات بعضها.",
    "What you see is a buy button. What happens is full market coordination across roles that never share screens.",
  ),
  techRationale: [
    techWhy(
      "كل دور يحتاج سطحًا سريعًا بالعربية دون تأخير كتالوج مشترك ثقيل.",
      "Each role needs a fast Arabic surface without a heavy shared-catalog lag.",
      "Next/React مع RTL يفصل تجارب الدور فوق نفس العقود.",
      "Next/React with RTL separates role UX over the same contracts.",
      ["Next.js 16", "React 19", "Tailwind 4"],
    ),
    techWhy(
      "عزل بيانات التاجر والطلب يجب أن يُفرض في قاعدة البيانات لا في الواجهة فقط.",
      "Merchant and order isolation must be enforced in the database—not only in the UI.",
      "RLS يربط الصفوف بالدور والسياق ويمنع تسرّب عبر الأدوار.",
      "RLS binds rows to role and context and blocks cross-role leakage.",
      ["Supabase", "RLS", "PostgreSQL"],
    ),
    techWhy(
      "إطلاق سوق جديد يحتاج بذور بيانات ومسارات اختبار للأدوار الأربعة.",
      "Launching a new market needs seeds and test paths for all four roles.",
      undefined,
      undefined,
      ["Seeds", "Integration tests", "Multi-role auth"],
    ),
  ],
  sector: "commerce",
  systemType: "commerce",
  status: "building",
  featured: true,
  region: ["Egypt"],
  roles: [
    role(
      "customer",
      "عميل",
      "Customer",
      "تصفح محلي، طلب واضح، وتتبع حتى التسليم.",
      "Local browse, a clear order, and tracking through delivery.",
      "كتالوج المنطقة، سلة، حالة الطلب، ومسار المندوب.",
      "Zone catalog, cart, order status, and courier path.",
      "يطلب ويدفع (حسب القواعد) ويتابع ويستلم.",
      "Orders, pays (per rules), tracks, and receives.",
      ["customer", "orders"],
      ["order", "delivery"],
    ),
    role(
      "merchant",
      "تاجر",
      "Merchant",
      "كتالوج ومخزون وقبول طلبات دون فقدان الطلب في الدردشة.",
      "Catalog, stock, and order acceptance without losing orders in chat.",
      "لوحة متجر: أصناف، توافر، طابور طلبات.",
      "Shop console: items, availability, order queue.",
      "يحدّث الكتالوج ويقبل/يرفض ويجهّز للمندوب.",
      "Updates catalog, accepts/rejects, and prepares for the courier.",
      ["merchant", "orders"],
      ["fulfill"],
    ),
    role(
      "courier",
      "مندوب",
      "Courier",
      "مهام استلام وتسليم بموقع وحالة — لا تنسيق هاتفي عشوائي.",
      "Pickup and delivery tasks with location and state—no random phone coordination.",
      "قائمة مهام، تفاصيل الاستلام، وتأكيد التسليم.",
      "Task list, pickup details, and delivery confirm.",
      "يستلم من التاجر ويسلّم للعميل ويغلق المهمة.",
      "Picks up from merchant, delivers to customer, closes the task.",
      ["courier", "orders"],
      ["delivery"],
    ),
    role(
      "admin",
      "إدارة المنصة",
      "Platform admin",
      "حوكمة المتاجر والمناطق والنزاعات دون الدخول في كل طلب يدويًا.",
      "Govern merchants, zones, and disputes without hand-running every order.",
      "سوق: متاجر، مناطق، سياسات، واستثناءات.",
      "Market: merchants, zones, policies, and exceptions.",
      "يفعّل المتاجر ويضبط المناطق ويحسم التصعيد.",
      "Activates merchants, configures zones, and resolves escalations.",
      ["admin", "orders"],
      ["governance", "exceptions"],
    ),
  ],
  modules: [
    mod(
      "customer",
      "تجربة العميل",
      "Customer experience",
      "تصفح وطلب وتتبع بواجهة عربية للمنطقة.",
      "Browse, order, and track in an Arabic zone-facing UI.",
      "يعطي العميل قناة رسمية بدل الرسائل المتفرقة.",
      "Gives the customer a formal channel instead of scattered messages.",
      "كتالوج منطقة، سلة، إنشاء طلب، وحالة حية.",
      "Zone catalog, cart, order create, and live status.",
      "يكتب في الطلبات ويقرأ من الكتالوج والتوصيل.",
      "Writes into orders; reads catalog and delivery.",
    ),
    mod(
      "merchant",
      "لوحة التاجر",
      "Merchant console",
      "كتالوج ومخزون وطابور طلبات للمتجر.",
      "Catalog, stock, and order queue for the shop.",
      "يمنع قبول طلب على صنف غير متاح أو مفقود من الدردشة.",
      "Stops accepting orders for unavailable items lost in chat.",
      "إدارة أصناف، توافر، وقبول/تجهيز.",
      "Item management, availability, accept/prepare.",
      "يغذي الكتالوج المشترك ودورة التنفيذ.",
      "Feeds the shared catalog and fulfillment cycle.",
    ),
    mod(
      "courier",
      "التوصيل",
      "Courier flows",
      "استلام وتسليم ميداني بحالات صريحة.",
      "Field pickup and delivery with explicit states.",
      "يربط حركة المندوب بالطلب لا بمكالمة منفصلة.",
      "Binds courier movement to the order—not a separate call.",
      "تعيين مهمة، تنقّل حالات، وتأكيد تسليم.",
      "Task assign, state transitions, delivery confirm.",
      "يحدّث الطلب ويُشعر العميل والتاجر.",
      "Updates the order and notifies customer and merchant.",
    ),
    mod(
      "admin",
      "إدارة المنصة",
      "Platform admin",
      "حوكمة السوق والمتاجر والمناطق والسياسات.",
      "Market, merchant, zone, and policy governance.",
      "يفصل تشغيل السوق عن تشغيل متجر واحد.",
      "Separates running the market from running a single shop.",
      "تفعيل متاجر، مناطق، سياسات، وتصعيد.",
      "Merchant activation, zones, policies, escalation.",
      "يشرف على كل الوحدات دون استبدال أدوارها.",
      "Oversees all modules without replacing their roles.",
    ),
    mod(
      "orders",
      "الطلبات",
      "Orders",
      "دورة حياة الطلب المشتركة بين كل الأدوار.",
      "Shared order lifecycle across every role.",
      "مصدر الحقيقة الوحيد لحالة ما طُلب وما دُفع وما سُلّم.",
      "The single source of truth for what was ordered, paid, and delivered.",
      "حالات من الإنشاء إلى الإغلاق مع قيود انتقال.",
      "States from create to close with transition constraints.",
      "المحور بين العميل والتاجر والمندوب والإدارة.",
      "Hub between customer, merchant, courier, and admin.",
    ),
  ],
  workflows: [
    wf(
      "order",
      "الطلب",
      "Order",
      [
        ["تصفح", "Browse"],
        ["طلب", "Order"],
        ["دفع", "Pay"],
        ["تأكيد", "Confirm"],
      ],
      "customer",
    ),
    wf(
      "fulfill",
      "التنفيذ",
      "Fulfillment",
      [
        ["قبول", "Accept"],
        ["تجهيز", "Prepare"],
        ["تسليم للمندوب", "Hand to courier"],
      ],
      "operations",
    ),
    wf(
      "delivery",
      "التوصيل",
      "Delivery",
      [
        ["استلام", "Pickup"],
        ["توصيل", "Deliver"],
        ["تأكيد", "Confirm"],
      ],
      "operations",
    ),
    wf(
      "governance",
      "حوكمة السوق",
      "Market governance",
      [
        ["تفعيل متجر", "Activate merchant"],
        ["ضبط منطقة", "Configure zone"],
        ["حسم نزاع", "Resolve dispute"],
      ],
      "management",
    ),
  ],
  integrations: [
    integ("delivery", "لوجستيات", "Logistics", "Delivery workflows", "تنسيق المندوبين وحالات التسليم", "Courier coordination and delivery states"),
    integ("catalog", "كتالوج", "Catalog", "Multi-vendor catalog", "مزامنة أصناف وتوافر المتاجر", "Merchant item and availability sync"),
    integ("msg", "رسائل", "Messaging", "WhatsApp / SMS", "إشعارات طلب وتسليم عند الحاجة", "Order and delivery notices when needed"),
  ],
  stack: [
    { layer: "frontend", items: ["Next.js 16", "React 19", "Tailwind 4"], responsibility: L("أسطح الأدوار بالعربية", "Arabic role surfaces") },
    { layer: "backend", items: ["Supabase", "RLS"], responsibility: L("عزل بيانات الأدوار والطلبات", "Role and order data isolation") },
    { layer: "data", items: ["PostgreSQL", "Seeds"], responsibility: L("كتالوج وطلبات ومناطق", "Catalog, orders, zones") },
    { layer: "ops", items: ["Multi-role auth", "Integration tests"], responsibility: L("إطلاق أسواق بثقة", "Confident market launches") },
  ],
  mass,
  capabilities: ["product", "ux", "frontend", "backend", "data", "operations"],
  outcomes: [
    { from: L("تنسيق واتساب يدوي", "Manual WhatsApp coordination"), to: L("دورة طلب رقمية مشتركة", "Shared digital order cycle") },
    { from: L("متجر واحد منفصل", "Isolated single store"), to: L("سوق متعدد الأدوار", "Multi-role market") },
    { from: L("مخزون وحالة في الرأس", "Stock and status in someone’s head"), to: L("كتالوج وحالات صريحة", "Explicit catalog and states") },
    { from: L("إعادة بناء لكل سوق", "Rebuild per market"), to: L("نفس البنية لمناطق جديدة", "Same infrastructure for new zones") },
  ],
  arkanScope: [
    L("استراتيجية المنتج", "Product strategy"),
    L("تجربة الاستخدام", "UX"),
    L("الواجهة", "Frontend"),
    L("الأنظمة الخلفية", "Backend"),
    L("البيانات", "Database"),
    L("التشغيل", "Operations"),
  ],
  relatedProjects: ["qr-menu", "sokany-commerce"],
  scale: scaleFromMass(mass, 5),
  dna: ["commerce", "supabase", "rtl", "multi-role"],
  atlas: { x: 18, y: 44 },
};
