import type { Project } from "../types";
import {
  L,
  mod,
  role,
  wf,
  integ,
  behind,
  techWhy,
  scaleFromMass,
} from "../projectBuilders";

const mass = {
  modules: 10,
  roles: 6,
  workflows: 5,
  interfaces: 4,
  integrations: 5,
  automations: 3,
  dataDomains: 8,
  locations: 2,
} as const;

export const veloraPos: Project = {
  id: "VLR-01",
  slug: "velora-pos",
  title: L("Velora POS", "Velora POS"),
  descriptor: L("تشغيل فروع ومبيعات", "Branch commerce operations"),
  summary: L(
    "نظام كاشير وإدارة فروع: مبيعات لمسية، مخزون متعدد المستودعات، جلسات صندوق، ولاء، وقائمة/طلبات أونلاين.",
    "Multi-location POS: touch selling, multi-warehouse stock, cash sessions, loyalty, and QR menu / online orders.",
  ),
  context: L(
    "مقاهي ومطاعم ومتاجر متعددة الفروع في مصر تحتاج تشغيل يومي واحد: كاشير سريع، مخزون دقيق بين الفروع، ورديات قابلة للمطابقة، وتقارير تنفيذية — لا أدوات متفرقة لكل وظيفة.",
    "Multi-branch cafés, restaurants, and shops in Egypt need one daily operating surface: fast cashier, accurate inter-branch stock, reconciliable shifts, and executive reporting — not a separate tool per function.",
  ),
  challenge: L(
    "المبيعات في جهاز، والمخزون في جدول، والورديات في دفتر، والطلبات الأونلاين في قناة ثالثة — فجوات في التحويل، خصم المخزون، وإغلاق الصندوق تمنع رؤية تشغيلية موثوقة.",
    "Sales on one device, stock in a spreadsheet, shifts in a notebook, online orders in a third channel — gaps in transfer, stock deduction, and cash close block trustworthy operational visibility.",
  ),
  thinking: L(
    "نقطة البيع ليست شاشة دفع؛ هي عقدة تشغيل تربط المنتج والمخزون والوردية والعميل والفرع. صمّمنا Velora كمنصة فروع بصلاحيات دقيقة وخصائص قابلة للتفعيل، بحيث يبقى مسار الكاشير سريعًا بينما تبقى الحوكمة خلفه.",
    "POS is not a payment screen; it is an operating node binding product, stock, shift, customer, and store. We designed Velora as a branch platform with precise permissions and feature flags so the cashier path stays fast while governance stays behind it.",
  ),
  solution: L(
    "واجهة لمسية للبيع مع جلسات صندوق، تحويلات ومخزون متعدد المستودعات، ولاء وعملاء، قائمة QR وطلبات أونلاين، وتقارير وتدقيق — فوق Supabase مع RLS وصلاحيات لكل مؤسسة/فرع.",
    "Touch-first selling with cash sessions, multi-warehouse transfers and stock, loyalty and customers, QR menu and online orders, plus reports and audit — on Supabase with RLS and org/store permissions.",
  ),
  impact: L(
    "من أدوات يومية متفرقة إلى تشغيل فروع موحّد: بيع، مخزون، وردية، وولاء على مسار بيانات واحد.",
    "From fragmented daily tools to unified branch operations: sales, stock, shift, and loyalty on one data path.",
  ),
  behindInterface: behind(
    "الكاشير يضغط «إتمام البيع»",
    "Cashier taps “Complete sale”",
    [
      [
        "التحقق من الجلسة المفتوحة وصلاحية الجهاز/المستخدم",
        "Validate open session and device/user permission",
      ],
      [
        "تسجيل بنود الطلب وطرق الدفع (نقدي/بطاقة/محفظة/تقسيم)",
        "Record order lines and payment methods (cash/card/wallet/split)",
      ],
      [
        "خصم المخزون عبر الوصفات أو الوحدات حسب إعدادات الفرع",
        "Deduct stock via recipes or units per store settings",
      ],
      [
        "تحديث الولاء وسجل العميل إن وُجد",
        "Update loyalty and customer ledger when attached",
      ],
      [
        "كتابة سجل تدقيق وإشارة طباعة الإيصال",
        "Write audit log and receipt print signal",
      ],
    ],
    "ضغطة واحدة تُغلق البيع عبر المخزون والصندوق والتتبع — لا مسار جانبي.",
    "One tap closes the sale across stock, cash, and audit — no side path.",
  ),
  techRationale: [
    techWhy(
      "واجهة لمسية سريعة على أجهزة الفروع",
      "Touch-fast UI on branch devices",
      "مسار الكاشير يجب أن يتحمل ضغط الوردية دون انتظار شاشات ثقيلة؛ Next.js وواجهة مخصّصة للمس تُبقي التفاعل قريبًا من الجهاز.",
      "The cashier path must survive shift pressure without heavy screens; Next.js and a touch-oriented UI keep interaction close to the device.",
      ["Next.js", "TypeScript", "Zustand"],
    ),
    techWhy(
      "عزل بيانات المؤسسة والفرع على مستوى قاعدة البيانات",
      "Org and store isolation at the database layer",
      "RLS وصلاحيات الأدوار تمنع تسرّب المخزون والمبيعات بين الفروع أو المستخدمين غير المصرّح لهم.",
      "RLS and role permissions prevent stock and sales leakage across stores or unauthorized users.",
      ["Supabase", "PostgreSQL", "RLS", "RBAC"],
    ),
    techWhy(
      "خصائص قابلة للتفعيل بدل بناء نسخة لكل عميل",
      "Feature flags instead of a fork per client",
      "الولاء، الطلبات الأونلاين، والخصم التلقائي للمخزون تُفعَّل حسب المؤسسة دون تشعّب الكود.",
      "Loyalty, online orders, and auto stock deduction toggle per organization without forking the codebase.",
      ["App settings", "Realtime settings"],
    ),
    techWhy(
      "تدقيق وتشغيل يومي قابل للمراجعة",
      "Auditable daily operations",
      "كل تغيير حساس على الإعدادات أو الإغلاق يُسجَّل؛ التقارير تُصدَّر للتشغيل لا للعرض فقط.",
      "Sensitive settings and close actions are logged; reports export for operations, not decoration.",
      ["Audit logs", "XLSX export", "Recharts"],
    ),
  ],
  sector: "commerce",
  systemType: "commerce",
  status: "operating",
  featured: true,
  region: ["Egypt"],
  roles: [
    role(
      "cashier",
      "كاشير",
      "Cashier",
      "بيع سريع، فتح/إغلاق وردية، وطباعة إيصال دون ضوضاء إدارية.",
      "Fast selling, open/close shift, and receipt print without admin noise.",
      "سلة، مدفوعات، جلسة صندوق، وعملاء مرتبطون بالطلب.",
      "Cart, payments, cash session, and customers attached to the order.",
      "إتمام بيع، تعليق سلة، استرداد ضمن السياسة، وطباعة.",
      "Complete sales, hold carts, refunds within policy, and print.",
      ["pos", "sessions", "loyalty"],
      ["sale", "shift"],
    ),
    role(
      "manager",
      "مدير فرع",
      "Branch manager",
      "رؤية مبيعات اليوم، المخزون الحرج، وإغلاق الوردية عبر الفريق.",
      "See today’s sales, critical stock, and shift close across the team.",
      "لوحات الفرع، الجلسات، التحويلات، والطلبات الأونلاين.",
      "Branch dashboards, sessions, transfers, and online orders.",
      "اعتماد تحويلات، مراجعة إغلاقات، وضبط عروض ضمن صلاحياته.",
      "Approve transfers, review closes, and tune promotions within scope.",
      ["reports", "inventory", "sessions", "online"],
      ["shift", "transfer", "online-order"],
    ),
    role(
      "inventory",
      "أمين مخزن",
      "Store keeper",
      "دقة الأرصدة بين المستودعات دون لمس شاشة البيع.",
      "Accurate balances across warehouses without touching the sell screen.",
      "مشتريات، تحويلات، هالك، وجرد.",
      "Purchases, transfers, waste, and stock counts.",
      "تسجيل حركات مخزون وإكمال جرد وربطها بالفرع.",
      "Post stock movements, complete counts, and bind them to the store.",
      ["inventory", "purchases", "transfers"],
      ["transfer", "count"],
    ),
    role(
      "owner",
      "مالك",
      "Owner",
      "حوكمة المؤسسات والفروع والمستخدمين والتقارير عبر الشبكة.",
      "Govern organizations, stores, users, and network-wide reporting.",
      "كل الفروع، الصلاحيات، الخصائص، والتقارير التنفيذية.",
      "All stores, permissions, feature flags, and executive reports.",
      "دعوة مستخدمين، تفعيل خصائص، وتصدير تقارير.",
      "Invite users, toggle features, and export reports.",
      ["system", "reports", "products", "loyalty"],
      ["sale", "shift", "online-order"],
    ),
    role(
      "kitchen",
      "مطبخ / تحضير",
      "Kitchen",
      "رؤية الطلبات الجاهزة للتحضير دون التعرض للصندوق.",
      "See orders ready to prepare without touching the cash drawer.",
      "طابور تحضير مرتبط بطلبات نقاط البيع أو الأونلاين.",
      "Prep queue bound to POS or online orders.",
      "تحديث حالة التحضير والتسليم الداخلي.",
      "Update prep and internal handoff status.",
      ["pos", "online"],
      ["sale", "online-order"],
    ),
    role(
      "admin",
      "مسؤول نظام",
      "System admin",
      "ضبط الكتالوج، الأجهزة، والصلاحيات دون كسر مسار البيع.",
      "Tune catalog, devices, and permissions without breaking the sell path.",
      "المستخدمون، الأجهزة، الإعدادات، وسجل التدقيق.",
      "Users, devices, settings, and audit log.",
      "إدارة أدوار، أزواج أجهزة، واستيراد/تصدير.",
      "Manage roles, device pairing, and import/export.",
      ["system", "products"],
      ["shift"],
    )
  ],
  modules: [
    mod(
      "pos",
      "نقطة البيع",
      "POS",
      "بيع لمسي: سلة، مدفوعات متعددة، وربط عميل.",
      "Touch selling: cart, multi-tender payments, customer attach.",
      "بطء الكاشير وتعدد شاشات الدفع.",
      "Slow checkout and fragmented tender screens.",
      "مسار بيع واحد مربوط بالجلسة والمخزون والإيصال.",
      "One sell path bound to session, stock, and receipt.",
      "يربط الجلسات، المنتجات، الولاء، والطلبات.",
      "Connects sessions, products, loyalty, and orders.",
    ),
    mod(
      "sessions",
      "جلسات الصندوق",
      "Cash sessions",
      "فتح وإغلاق وردية مع مطابقة نقدية.",
      "Shift open/close with cash reconciliation.",
      "إغلاقات غير موثوقة وفروقات صندوق غير مفسَّرة.",
      "Untrusted closes and unexplained cash variances.",
      "جلسة لكل كاشير/جهاز مع سجل حركات.",
      "Per cashier/device session with movement ledger.",
      "يربط نقاط البيع والتقارير والتدقيق.",
      "Connects POS, reports, and audit.",
    ),
    mod(
      "inventory",
      "المخزون",
      "Inventory",
      "أرصدة ومستودعات متعددة لكل فرع.",
      "Balances and multi-warehouse stock per store.",
      "انقطاع الرؤية بين ما يُباع وما يُخزَّن.",
      "Blind spot between what sells and what is stored.",
      "حركات مخزون لحظية وخصم عبر وصفات عند الحاجة.",
      "Live stock movements and recipe deduction when needed.",
      "يربط المشتريات والتحويلات والجرد والهالك.",
      "Connects purchases, transfers, counts, and waste.",
    ),
    mod(
      "transfers",
      "تحويلات الفروع",
      "Transfers",
      "تحويل مخزون بين الفروع والمستودعات.",
      "Stock transfer between stores and warehouses.",
      "نقل يدوي بلا أثر وتشغيل متضارب بين الفروع.",
      "Manual moves with no trail and conflicting branch ops.",
      "أوامر تحويل بحالات وموافقة حسب الصلاحية.",
      "Transfer orders with states and permissioned approval.",
      "يربط المخزون والتقارير والمدير.",
      "Connects inventory, reports, and manager flows.",
    ),
    mod(
      "purchases",
      "المشتريات",
      "Purchases",
      "فواتير شراء وموردون وتكلفة واردة.",
      "Purchase invoices, suppliers, and landed cost.",
      "تكلفة غير مربوطة بالمخزون.",
      "Cost unlinked from stock.",
      "إدخال فواتير يحدّث الأرصدة والتكلفة.",
      "Invoice entry updates balances and cost.",
      "يربط الموردين والمخزون والمصروفات.",
      "Connects suppliers, inventory, and expenses.",
    ),
    mod(
      "products",
      "المنتجات والوصفات",
      "Products & recipes",
      "كتالوج، متغيرات، ومكوّنات للخصم.",
      "Catalog, variants, and recipe components for deduction.",
      "قوائم منتجات غير متسقة عبر الفروع.",
      "Inconsistent catalogs across stores.",
      "منتج واحد بسياسات سعر ووصفة قابلة للتحكم.",
      "One product with controllable price and recipe policies.",
      "يربط نقطة البيع والمخزون والقائمة الأونلاين.",
      "Connects POS, inventory, and online menu.",
    ),
    mod(
      "loyalty",
      "الولاء والعملاء",
      "Loyalty & customers",
      "ملفات عملاء، نقاط، وسجل شراء.",
      "Customer profiles, points, and purchase history.",
      "عملاء مجهولون وعروض بلا أثر.",
      "Anonymous customers and promotions with no trail.",
      "كسب/استبدال نقاط مربوط بإتمام البيع.",
      "Earn/redeem points bound to sale completion.",
      "يربط نقطة البيع والتقارير والعروض.",
      "Connects POS, reports, and promotions.",
    ),
    mod(
      "online",
      "القائمة والطلبات الأونلاين",
      "Online menu & orders",
      "قائمة عامة وطلبات طرف أول للفروع.",
      "Public menu and first-party orders for stores.",
      "قناة أونلاين منفصلة عن المخزون والكاشير.",
      "Online channel disconnected from stock and cashier.",
      "قائمة QR وطلبات تدخل طابور التشغيل نفسه.",
      "QR menu and orders enter the same ops queue.",
      "يربط المنتجات ونقطة البيع والتقارير.",
      "Connects products, POS, and reports.",
    ),
    mod(
      "reports",
      "التقارير",
      "Reports",
      "مبيعات، جلسات، مخزون، ربح، وتصدير.",
      "Sales, sessions, stock, profit, and export.",
      "قرارات يومية بلا أرقام موثوقة من النظام.",
      "Daily decisions without trustworthy system numbers.",
      "لوحات وتنزيلات XLSX من نفس مصدر الحقيقة.",
      "Dashboards and XLSX downloads from one source of truth.",
      "يربط كل وحدات التشغيل بالإدارة.",
      "Connects all operating modules to management.",
    ),
    mod(
      "system",
      "النظام والصلاحيات",
      "System & permissions",
      "مستخدمون، أدوار، أجهزة، إعدادات، وتدقيق.",
      "Users, roles, devices, settings, and audit.",
      "صلاحيات فضفاضة وتغييرات بلا أثر.",
      "Loose permissions and untracked configuration changes.",
      "RBAC وخصائص وإعدادات لحظية مع سجل تدقيق.",
      "RBAC, feature flags, realtime settings, and audit log.",
      "يربط كل الوحدات بهوية المؤسسة.",
      "Connects every module to organization identity.",
    ),
  ],
  workflows: [
    wf(
      "sale",
      "البيع",
      "Sale",
      [
        ["فتح جلسة", "Open session"],
        ["إضافة منتجات", "Add products"],
        ["دفع", "Pay"],
        ["خصم مخزون", "Deduct stock"],
        ["إيصال", "Receipt"],
      ],
      "customer",
    ),
    wf(
      "shift",
      "الوردية",
      "Shift",
      [
        ["فتح صندوق", "Open cash"],
        ["بيع خلال الوردية", "Sell during shift"],
        ["مطابقة", "Reconcile"],
        ["إغلاق", "Close"],
      ],
      "operations",
    ),
    wf(
      "transfer",
      "تحويل المخزون",
      "Stock transfer",
      [
        ["طلب تحويل", "Request transfer"],
        ["موافقة", "Approve"],
        ["شحن/استلام", "Ship / receive"],
        ["تحديث أرصدة", "Update balances"],
      ],
      "operations",
    ),
    wf(
      "online-order",
      "طلب أونلاين",
      "Online order",
      [
        ["مسح قائمة QR", "Scan QR menu"],
        ["طلب", "Order"],
        ["استلام تشغيلي", "Ops intake"],
        ["تحضير / تسليم", "Prep / fulfill"],
      ],
      "customer",
    ),
    wf(
      "count",
      "الجرد",
      "Stock count",
      [
        ["بدء جرد", "Start count"],
        ["عدّ البنود", "Count lines"],
        ["فروقات", "Variances"],
        ["اعتماد", "Post"],
      ],
      "operations",
    ),
  ],
  integrations: [
    integ(
      "qr-menu",
      "قائمة",
      "Menu",
      "First-party QR menu",
      "قائمة رقمية وطلبات مربوطة بالفرع",
      "Digital menu and orders bound to the store",
    ),
    integ(
      "payments",
      "مدفوعات",
      "Payments",
      "Multi-tender checkout",
      "نقدي وبطاقة ومحفظة وتقسيم دفع",
      "Cash, card, wallet, and split tender",
    ),
    integ(
      "auth",
      "هوية",
      "Identity",
      "Supabase Auth",
      "تسجيل دخول وصلاحيات مؤسسة/فرع",
      "Sign-in with org/store authorization",
    ),
    integ(
      "export",
      "بيانات",
      "Data",
      "XLSX import / export",
      "استيراد كتالوج وتصدير تقارير تشغيلية",
      "Catalog import and operational report export",
    ),
    integ(
      "print",
      "طباعة",
      "Print",
      "Receipt / label print",
      "إيصالات وملصقات من جهاز الفرع",
      "Receipts and labels from the branch device",
    ),
  ],
  stack: [
    {
      layer: "interface",
      items: ["Next.js 16", "React 19", "Tailwind 4", "shadcn/ui", "RTL"],
      responsibility: L(
        "أسطح الكاشير والإدارة والقائمة العامة",
        "Cashier, admin, and public menu surfaces",
      ),
    },
    {
      layer: "application",
      items: ["Server Actions", "Zustand", "Zod", "Feature flags"],
      responsibility: L(
        "منطق البيع والمخزون والصلاحيات",
        "Sale, inventory, and permission logic",
      ),
    },
    {
      layer: "data",
      items: ["Supabase", "PostgreSQL", "RLS", "Realtime settings"],
      responsibility: L(
        "بيانات المؤسسة والفرع مع عزل صارم",
        "Org/store data with strict isolation",
      ),
    },
    {
      layer: "business",
      items: ["RBAC", "Sessions", "Recipes", "Loyalty ledger"],
      responsibility: L(
        "قواعد التشغيل اليومية للفروع",
        "Daily branch operating rules",
      ),
    },
    {
      layer: "ops",
      items: ["Audit logs", "Device pairing", "XLSX", "Recharts"],
      responsibility: L(
        "مراجعة وتشغيل وتقارير",
        "Review, operations, and reporting",
      ),
    },
  ],
  mass: { ...mass },
  capabilities: [
    "product",
    "ux",
    "frontend",
    "backend",
    "data",
    "integrations",
    "operations",
  ],
  outcomes: [
    {
      from: L("أدوات منفصلة", "Disconnected tools"),
      to: L("تشغيل فروع موحّد", "Unified branch ops"),
    },
    {
      from: L("مخزون أعمى", "Blind stock"),
      to: L("أرصدة مربوطة بالبيع", "Balances tied to sales"),
    },
    {
      from: L("إغلاق صندوق تقديري", "Guesswork cash close"),
      to: L("وردية قابلة للمطابقة", "Reconciliable shift"),
    },
    {
      from: L("قناة أونلاين منفصلة", "Separate online channel"),
      to: L("طلبات على نفس المسار", "Orders on the same path"),
    },
  ],
  arkanScope: [
    L("استراتيجية المنتج", "Product strategy"),
    L("معمارية النظام", "System architecture"),
    L("تجربة الاستخدام", "UX"),
    L("الواجهة", "Frontend"),
    L("الأنظمة الخلفية", "Backend"),
    L("البيانات والصلاحيات", "Data & permissions"),
    L("التكاملات", "Integrations"),
    L("التشغيل", "Operations"),
  ],
  relatedProjects: ["qr-menu", "souqna"],
  scale: scaleFromMass(mass, 5),
  dna: ["pos", "multi-store", "supabase", "rtl", "rbac"],
  atlas: { x: 48, y: 18 },
};
